cozy-mate/cozymate-Server

- src/main/java/com/cozymate/cozymate_server/domain/todo/controller/TodoController.java
- src/main/java/com/cozymate/cozymate_server/global/utils/SwaggerApiError.java
- src/main/java/com/cozymate/cozymate_server/global/utils/SwaggerApiErrorCustomizer.java
- Swagger 에러 관련 어노테이션입니다.
- 아래 이미지 참고!
- 어노테이션 관련 세팅입니다.
```java
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface SwaggerApiError {
ErrorStatus[] value();
}
```
- 어노테이션이 들어왔을 때 커스텀합니다.
- SwaggerApiError 값을 가져옵니다.
``` java
@Component
public class SwaggerApiErrorCustomizer implements OperationCustomizer {
@Override
public Operation customize(Operation operation, HandlerMethod handlerMethod) {
SwaggerApiError swaggerApiError = handlerMethod.getMethodAnnotation(SwaggerApiError.class);
```
- 값이 있을 때에만 각각 진행합니다.
``` java
if (swaggerApiError != null) {
Map<String, List<Map<String, Object>>> errorDetailsMap = new HashMap<>();
for (ErrorStatus errorStatus : swaggerApiError.value()) {
String statusCode = String.valueOf(errorStatus.getHttpStatus().value()); …
```
> [COZY-39] Swagger Custom Error Annotation 구현

- src/main/java/com/cozymate/cozymate_server/domain/chat/controller/ChatController.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/converter/ChatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/dto/ChatResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/repository/ChatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/service/ChatQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- src/test/java/com/cozymate/cozymate_server/domain/chat/ChatTestBuilder.java
- src/test/java/com/cozymate/cozymate_server/domain/chat/service/ChatQueryServiceTest.java
쪽지방의 쪽지 상세 내역 조회를 구현했습니다.
```java
//ChatController.java
// TODO: memberId는 추후 시큐리티 인증 객체에서 받아 오는 것으로 변경 예정
@GetMapping("/chatrooms/{chatRoomId}")
@Operation(summary = "[베로] 쪽지방의 쪽지 상세 내역 조회", description = "내 memberId, chatRoomId : 조회할 쪽지방 pk값")
public ResponseEntity<List<ChatResponseDto>> getChatList(@RequestParam Long memberId,
@PathVariable Long chatRoomId) {
return ResponseEntity.ok(chatQueryService.getChatList(memberId, chatRoomId));
}
```
```java
//ChatQueryService.java
public List<ChatResponseDto> getChatList(Long memberId, Long chatRoomId) {
Member member = memberRepository.findById(memberId)
.orElseThrow(() -> new GeneralException(ErrorStatus._MEMBER_NOT_FOUND));
ChatRoom chatRoom = chatRoomRepository.findById(chatRoomId)
.orElseThrow(() -> new …
```
> [COZY-48] 쪽지방의 쪽지 상세 내역 조회 API

- src/main/java/com/cozymate/cozymate_server/domain/auth/controller/KakaoController.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/controller/SocialLoginController.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/dto/AuthResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/repository/TokenRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/service/AuthService.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/service/KakaoService.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/service/LogoutService.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/service/SocialLoginService.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/userDetails/MemberDetails.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/userDetails/TemporaryMember.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/AuthConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/ClientIdMaker.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtFilter.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/MemberResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/enums/Gender.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/config/SecurityConfig.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- 사용자 탈퇴 API 기능 구현했습니다.
- 소셜로그인 하면서 좁 더럽던 구조 리팩토링 했습니다.
- 토큰 발급 access token 값 response 헤더 말고 바디에 담았습니다.
MemberController
```java
@Operation(summary = "[말즈] 회원 탈퇴 API", description = "현재 로그인한 사용자를 탈퇴시킵니다.")
@DeleteMapping("/withdraw")
public ResponseEntity<ApiResponse<String>> withdraw(@AuthenticationPrincipal MemberDetails memberDetails) {
memberCommandService.withdraw(memberDetails);
return ResponseEntity.status(SuccessStatus._OK.getHttpStatus())
.body(ApiResponse.onSuccess("회원 탈퇴가 완료되었습니다."));
}
```
MemberService
```java
public void withdraw(MemberDetails memberDetails){
memberRepository.delete(memberDetails.getMember());
}
```
```java
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class …
```
> [COZY-162] 사용자 탈퇴 API 추가 및 코드 구조 리팩토링, AccessToken 발급 Body로 옮기기

- .gitignore
- src/main/java/com/cozymate/cozymate_server/domain/todo/converter/TodoConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/dto/TodoResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoQueryService.java
- 간단하니 그냥 코드로 봐주세용
- 각 사용자마다 Persona 번호도 줘야해서 해당 Response를 추가했습니다.
- Map에 사용자가 연관되어서 코드가 좀 바뀐게 있지만, 실제로는 그냥 한 겹을 더 씌운 느낌입니다.
- 아래처럼 이미지에 persona 번호가 존재합니다.
- ResponseDto의 innerclass 이름들이 맘에 안드는데, 좀 고민해볼게용
> [COZY-183] refac: Todo 반환 형식에 Persona 추가

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/util/MemberUtil.java
타인의 멤버 상세정보를 볼 때 멤버 ID를 이용해서 조회하고,
OS 별로 일치율 조회를 위해 필요한 API가 달라 안드로이드가 사용할 수 있는 API를 만들었습니다.
IOS : 기존 API 사용
Android:  일치율 조회에 사용자 상세정보 포함한 API 제작
코드를 재사용하기 위해 다음과 같이 구현했습니다.
```java
public PageResponseDto<List<?>> getMemberStatList(Member member,
List<String> filterList, Pageable pageable, boolean needsDetail) {
//일치율의 기준이 되는 MemberStat을 가져오고, 유효성을 검사합니다.
MemberStat criteriaMemberStat = memberStatRepository.findByMemberId(member.getId())
.orElseThrow(
() -> new GeneralException(ErrorStatus._MEMBERSTAT_NOT_EXISTS)
);
//필터링된 리스트들을 가져옵니다. 필터가 없을 경우, 모두 가져옵니다.
List<MemberStat> filteredResult = memberStatRepository.getFilteredMemberStat(filterList,
criteriaMemberStat);
if (filteredResult.isEmpty()) {
return new PageResponseDto<>(pageable.getPageNumber(), false, Collections.emptyList());
}
if …
```
> [COZY-182] 멤버 상세정보 멤버 ID로 조회 및 일치율 조회 각 OS 별 분리

- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/RoomLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/controller/RoomLogController.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/converter/RoomLogConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/dto/RoomLogRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/dto/RoomLogResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/repository/RoomLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogQueryService.java
- Room Log 조회 기능부터 구현했습니다.
- 단순히 가져와서 조회하는 기능이며 + Pagenation이 구현되어있습니다.
- Pagenation의 기본값도 지정해두었습니다.
- 단순히 Room Log를 생성일 기준으로 최신순으로 정렬한 후 가져와서 형식에 맞게 반환합니다.
```java
public PageResponseDto<List<RoomLogDetailResponseDto>> getRoomLogList(
Long roomId,
Member member,
int page,
int size) {
// 본인 방에 속한건지 확인
Mate mate = mateRepository.findByMemberIdAndRoomId(member.getId(), roomId)
.orElseThrow(() -> new GeneralException(ErrorStatus._MATE_OR_ROOM_NOT_FOUND));
Pageable pageable = PageRequest.of(page, size);
Slice<RoomLog> roomLogSlice = roomLogRepository.findAllByRoomIdOrderByCreatedAtDesc(roomId,
pageable);
List<RoomLogDetailResponseDto> roomLogResponseList = roomLogSlice.getContent().stream()
.map(RoomLogConverter::toRoomLogDetailResponseDto)
.toList();
return new …
```
> [COZY-38] feat: Room Log 조회 기능 구현

- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/service/RuleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/controller/TodoController.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
- Todo 삭제 기능을 구현했습니다.
-TodoId 값을 받아서, 해당 Todo의 주인이 본인이라면 삭제되도록 하고, 아니라면 에러가 반환되도록 했습니다.
```java
public void deleteTodo(
Member member,
Long todoId
) {
Todo todo = todoRepository.findById(todoId)
.orElseThrow(() -> new GeneralException(ErrorStatus._TODO_NOT_FOUND));
if (Boolean.FALSE.equals(todo.getMate().getMember().getId().equals(member.getId()))) {
throw new GeneralException(ErrorStatus._TODO_NOT_VALID);
}
todoRepository.delete(todo);
}
```
- 아래처럼 9번에 해당하는 투두가 있다고 했을 때
- Todo Id로 삭제를 진행하면 200 성공이 반환됩니다.
- 다시 호출하면 이젠 없습니다.
> [COZY-29] feat: Todo 삭제 기능 구현

- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/CozymateInfoResponse.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomCreateResponse.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
방 정보 조회 시 mateId 포함했습니다.
```java
@Getter
@Builder
public class CozymateInfoResponse {
private Long memberId;
private Long mateId;
private String nickname;
}
```
나머지 적용 방식은 #70 과 동일합니다.
성공~
> 감사합니다
> [COZY-198] 방 정보 조회 시 mateId 포함

- src/main/java/com/cozymate/cozymate_server/domain/feed/controller/FeedController.java
- src/main/java/com/cozymate/cozymate_server/domain/feed/converter/FeedConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
1. 방 생성시 피드 자동 생성
2. 멤버 상세정보 삭제 (APP에서 사용 불가능하게)
2번 상황은 혹시 모를 상황을 대비해서 삭제 API를 구현해놨습니다.
관리자 페이지를 추후에 구현한다면, 거기에서도 사용할 것 같아 구현했습니다.
1. Room 코드 수정
```java
Feed feed = FeedConverter.toEntity(room);
feedRepository.save(feed);
```
2. MemberStat 삭제 코드
```java
public void deleteMemberStat(Long memberId){
if(!memberStatRepository.existsById(memberId)){
throw new GeneralException(ErrorStatus._MEMBER_NOT_FOUND);
}
MemberStat memberStat = memberStatRepository.findByMemberId(memberId).orElseThrow(
() -> new GeneralException(ErrorStatus._MEMBERSTAT_NOT_EXISTS)
);
memberStatRepository.delete(memberStat);
}
```
Room 삭제 관련해서 Feed 존재 여부를 검사하는 코드가 있는데,
이 부분은 아직 Room이 생성되었어도, Feed가 존재하지 않는 경우가 DB에 남아있어,
추후에 DB를 밀게 되면 그때 변경하면 될 거 같습니다. @suuu0719 
제 방이 없어 생성했습니다
방 생성시 피드가 잘 생성된 것을 확인했습니다
현재 존재하는 포비 정보
삭제. …
> [COZY-202] feat: 방 생성시 피드 자동 생성, 멤버 상세정보 삭제 기능

- src/main/java/com/cozymate/cozymate_server/domain/fcm/dto/FcmPushContentDto.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/dto/FcmPushTargetDto.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/FcmPushService.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/enums/NotificationType.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/repository/TodoRepository.java
- src/main/java/com/cozymate/cozymate_server/global/event/EventListener.java
- src/main/java/com/cozymate/cozymate_server/global/scheduler/NotificationScheduler.java
방 입장 시 해당 방의 메이트들에게 알림 전송 기능 구현했습니다.
스케줄러에서 FcmPushService의 비동기 메서드 호출 시 -> 트랜잭션 분리로 영속성 컨텍스트가 달라져버려 프록시 초기화 안되는 문제 발생
-> 스케줄러 단에서 조회시 페치 조인으로 가져와서 해결했습니다.
```java
```
>
> [COZY-234] 방 입장 시 알림, 스케줄러 알림 전송 비동기로 처리

- .github/scripts/pr_review.py
- .github/workflows/pr_review_bot.yml
> [COZY-243] feat: 리뷰 워크플로우 추가

- .github/scripts/pr_review.py
Sonnet에서 Haiku로 수정입니다.
(코드 길이가 길어서 토큰 소비가 많을 것 같기에..)
```java
```
>
> [COZY-243] feat: 모델 변경

- src/main/java/com/cozymate/cozymate_server/domain/friend/controller/FriendController.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/enums/FriendStatus.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/service/FriendQueryService.java
친구인지 아닌지, 친구 요청 대기중인지 조회해주는 API입니다.
친구 목록 조회하는 API 경로를 수정했습니다.
이 API는 다음 화면에서 사용하려고 만들었습니다.
간단간단한 로직입니다.
1. 나에게 요청 보낸건지 검사
2. 친구 요청이 있는지 검사하고, 있다면 해당 STATUS 리턴
3. 없다면 STRANGER ENUM 리턴
```java
public FriendStatus getFriendStatus(Member member, Long friendId) {
// 요청하는 사람과 수락하는 사람이 같은지 검사
if (member.getId().equals(friendId)) {
throw new GeneralException(ErrorStatus._FRIEND_REQUEST_EQUAL);
}
return friendRepository.findBySenderIdAndReceiverIdOrReceiverIdAndSenderId(
member.getId(), friendId, member.getId(), friendId
)
.map(Friend::getStatus)
.orElse(FriendStatus.STRANGER);
}
```
낯선 사람일 때
친구 요청이 대기중일 때
친구 요청을 수락했을 때
> ENUM에 STRANGER라는 경우의 수를 추가하긴 했는데, DB에는 영향이 없습니다.
> 적절한 방식인지는 잘 모르겠는데 더 좋은 방법 아시는 분은 공유 부탁드립니다~
> [COZY-203] feat: 친구 상태 조회

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/util/MemberUtil.java
다른 도메인에서 사용자 일치율이 사용되는 것 같아, 다른 곳에서 사용할 수 있도록 분리했습니다.
또한 저번 회의에서 반영된 일치율에서 성격을 제거하는 부분을 수정했습니다.
toEqualityResponse static 클래스를 calculateScore로 바꾸고, 일치율을 int로 리턴하게 바꿨습니다.
toEqualityResponse에서 Dto를 리턴했었는데, 이를 Converter로 옮겼습니다.
코드도 옮긴거 밖에 없어서 따로 작성하지 않겠습니다.
잘 작동하는 것을 확인했습니다.
>  방 관련 도메인에서 해당 기능을 사용해야할 거 같아, 인지하고 계시면 되겠습니다. @suuu0719
> [COZY-252] feat: 일치율 계산 관련 Util 분리, 성격 일치율 계산에서 제거

- src/main/java/com/cozymate/cozymate_server/domain/chat/controller/ChatController.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/MemberBlock.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/controller/MemberBlockController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/converter/MemberBlockConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/dto/MemberBlockRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/dto/MemberBlockResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/repository/MemberBlockRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/service/MemberBlockCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/service/MemberBlockQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
화면은 아직 안나왔지만,
1. 차단, 차단 해제, 차단 목록 조회를 구현했습니다.
2. 쪽지방 목록 조회에 차단에 대한 처리를 추가했습니다.
```java
// MemberBlockCommandService.java (차단)
public void saveMemberBlock(MemberBlockRequestDto requestDto, Member member) {
// 1
if (requestDto.getBlockedMemberId().equals(member.getId())) {
throw new GeneralException(ErrorStatus._CANNOT_BLOCK_OWN);
}
// 2
checkDuplicatedBlock(requestDto, member);
// 3
Member blockedMember = memberRepository.findById(requestDto.getBlockedMemberId())
.orElseThrow(() -> new GeneralException(ErrorStatus._MEMBER_NOT_FOUND));
// 4
MemberBlock memberBlock = MemberBlockConverter.toEntity(member, blockedMember);
memberBlockRepository.save(memberBlock);
}
private void checkDuplicatedBlock(MemberBlockRequestDto …
```
> [COZY-260] feat : 유저 차단 기능 구현

- build.gradle
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/ClientIdMaker.java
- src/main/java/com/cozymate/cozymate_server/domain/mail/controller/MailController.java
- src/main/java/com/cozymate/cozymate_server/domain/mail/dto/MailRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/mail/dto/MailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/mail/service/MailService.java
메일 보내기 기능을 추가했습니다.
아직 메일 패턴적용은 안했구여.. 인증코드 생성해서 메일 보내고, 검증하는 api만 만들었습니다.
일단 지금은 자바 맵으로 구현했습니다.
```java
public void sendUniversityAuthenticationCode(String clientId, String mailAddress) {
SimpleMailMessage message = new SimpleMailMessage();
String authCode = UUID.randomUUID().toString().substring(0, 6);
message.setTo(mailAddress);
message.setSubject("COZYMATE 대학교 메일인증");
message.setText("COZYMATE 대학교 메일인증 코드입니다 : " + authCode);
mailSender.send(message);
memberAuthenticationCodeMap.put(clientId, authCode);
}
```
6자리 코드를 만들어 메일을 보내는 코드입니다.
```java
public MailResponseDTO.verifyResponseDTO verifyAuthenticationCode(String clientId, String authenticationCode) {
if (memberAuthenticationCodeMap.get(clientId).equals(authenticationCod …
```
> [COZY-232] feat : 메일 인증 기능 추가

- src/main/java/com/cozymate/cozymate_server/domain/hashtag/Hashtag.java
- src/main/java/com/cozymate/cozymate_server/domain/hashtag/converter/HashtagConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/hashtag/repository/HashtagRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/Mate.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/enums/EntryStatus.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/Room.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/PublicRoomCreateRequest.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomCreateResponse.java
- src/main/java/com/cozymate/cozymate_server/domain/room/enums/RoomType.java
- src/main/java/com/cozymate/cozymate_server/domain/room/repository/RoomRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomhashtag/RoomHashtag.java
- src/main/java/com/cozymate/cozymate_server/domain/roomhashtag/converter/RoomHashtagConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/roomhashtag/repository/RoomHashtagRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomhashtag/service/RoomHashtagCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- 공개방/초대코드 방 만들기 구분
- 공개방
- 공개방은 해시태그 1~3개 작성해야함
- 공개방은 정원 모두 입장할때까지 WAITING 상태
- 비공개방
- 해시태그 기능 없음
- 만들어지는 순간 ENABLE 상태가 된다
- 방 이름 중복 검사 추가
- 해시태그
- Room, RoomHashtag, Hashtag로 엔티티 분리함
- RoomHashtag에서 Room과 Hashtag 다대다 매핑
- 방 나가기
- 모두 나가기 전까지 방은 삭제 되지 않는다.
- 최후의 1인이 나가는 순간 방이 사라진다 → 이때 데이터를 다 날림
- isExit 사용, entryStatus에 EXITED 추가 (밑에 자세히..)
- 방 입장
- 방나가기를 만들면서 재입장을 고려해야함
- 재입장하는 경우/처음 입장하는 경우로 구분
```java
// RoomController
@PostMapping("/create-private")
@Operation(summary = "[바니] 초대코드로 방생성 기능", description = "방이름, 프로필이미지, 인원수를 입력합니다.")
@SwaggerApiError({
ErrorStatus._MEMBER_NOT_FOUND,
ErrorStatus._ROOM_ALREADY_EXISTS
})
public ResponseEntity<ApiResponse<RoomCreateResponse>> createRoom(@Valid @RequestBody RoomCreateRequest request,
@AuthenticationPrincipal MemberDetails memberDetails) { …
```
> [COZY-259] feat : 방로직 전체적 수정 및 방나가기 구현

- src/main/java/com/cozymate/cozymate_server/domain/rule/Rule.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/controller/RuleController.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/dto/RuleRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/dto/RuleResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/service/RuleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/service/RuleQueryService.java
1. 주석을 추가하고 분리할 수 있는 함수를 분리하였습니다.
2. Rule 수정 기능을 추가했습니다.
3. Rule 파트의 엔드포인트를 수정하였고, RESTFul할 수 있을만큼 만들어보았습니다.
1. 주석을 추가하고 분리할 수 있는 함수를 분리하였습니다.
- 해당 부분은 코드를 좀 더 읽기 쉽게, 재사용 가능하도록 수정하는 리팩토링이라 코드 변경사항을 확인해주세요.
2. Rule 수정 기능을 추가했습니다.
- Rule의 값을 찾아서 데이터를 덮어씌우는 방식으로 구현했습니다.
- 수정하고자 하는 부분의 데이터만 수정하고자 했을 때 memo의 값이 nullable이라, memo의 데이터를 수정하고싶은지(null로 바꾸고 싶은지) 아니면 데이터를 수정하고싶지 않은지(그대로 두고싶은지)에 대한 판단이 애매하다고 생각했습니다.
- 따라서 프론트에서 content, memo의 값을 모두 다시 주면 해당 값을 덮어씌우는 방식으로 구성되도록 하였습니다.
- 이에 따라 PATCH 방식(일부 수정)으로 보내는 API를 PUT 방식(전체 수정)으로 보내는 API로 변경하였습니다.
3. Rule 파트의 엔드포인트를 수정하였고, RESTFul할 수 있을만큼 일부 수정해보았습니다.
- API의 Endpoint가 명확하지 않다고 느꼈고, RoomId는 항상 Mate를 구하기 위한 필수 데이터였습니다. 따라서 room에 종속되어있다고 보았고, 이에 따라 Endpoint를 계층화 하고자 하였습니다.
- 기존에 `/rules/{roomId}/{ruleId}` 의 형식에서 `/rooms/{roomId}/rules/{ruleId}`의 형식으로 …
> [COZY-36] Rule 관련 전체 기능 리팩토링

- build.gradle
- src/main/java/com/cozymate/cozymate_server/global/config/SshDataSourceConfig.java
- src/main/java/com/cozymate/cozymate_server/global/config/SshRedisConfig.java
- src/main/java/com/cozymate/cozymate_server/global/config/SshTunnelConfig.java
- src/main/java/com/cozymate/cozymate_server/global/redis/test/Test.java
- src/main/java/com/cozymate/cozymate_server/global/redis/test/TestRepository.java
- src/main/java/com/cozymate/cozymate_server/global/redis/test/TestService.java
- Redis 관련 정보 서브모듈에 추가
- SSH 터널링을 사용하면서, 접속 config 추가, 기존 코드 수정
- RedisConfig로 템플릿 추가
- global 패키지에 redis 패키지 추가 -> 여기서 key-value로 관리해주세요
- Test 엔티티 추가해서 예시코드 추가 -> 이거 가져다가 변경해서 대충 쓰면 됩니당
요약이 곧 내용입니당
대충 컨트롤러에 끼워서 넣으니 잘 동작합니당
이건 키 추가된 결과 (Redis Insight 쓰세요 최고의 관리툴)
- 음 도메인 구조를 이렇게 해둔 이유는 일단
1. Repository로 등록된 클래스 (JpaRepository, CrudRepository)면 DB에서 인식을 합니다.
2. 나누지 않으면 RDS랑 Redis가 동일한 Repository를 자기가 사용할 인터페이스라고 생각합니다.
3. 그래서 @EnableJpaRepositories를 사용할 때 basePackages를 나눠서 각자 사용할 레포지토리가 있을 위치를 정해줘야합니다.
4. 그러다보니 그냥 domain이랑 global이랑 구분해서 domain에서 사용하는 repository는 JpaRepository이고, global에서 redis 도메인에서 사용하는건 Redis인걸로 처리해뒀습니다.
더 나은 의견, 더 좋은 생각, 잘못된 부분 의견받습니당
> [COZY-281] feat: Redis 세팅 추가

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/MemberStat.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/MemberStatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/querydsl/MemberStatQueryRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/querydsl/MemberStatQueryRepositoryImpl.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/util/MemberStatUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/MemberStatEquality.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/controller/MemberStatEqualityController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/repository/MemberStatEqualityBulkRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/repository/MemberStatEqualityRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/service/MemberStatEqualityCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/service/MemberStatEqualityQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/util/MemberStatEqualityUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/enums/NotificationType.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- MemberStat 기획 변경 적용
- 상세 필터링 검색 기능 구현
- 일치율 계산 및 조회 방식 변경
3가지가 모두 묶여 있는 것들이라.. PR을 이렇게 몰아서 하게 된 점 죄송합니다.
테스트라도 보시면서.. 즐겨주세요
**1. Boolean → String**
1. 3가지 멤버변수가 String으로 수정되었습니다.
- canShare, isPlayGame, isPhoneCall
**2. 다중 선택 타입 추가 (잠꼬대, 성격) :star: 중요!**
1. 저장 방식
- 항목들을 저장할 때 구분자로, 를 사용하고 정렬함. EX) '조용해요,활발해요, 말이 많아요,'
2. Util을 사용해 배열 → String 저장, String → 배열 읽기
- MemberStatUtil에 구현했습니다.
2. 방식 사용 이유
- 다른 연관관계를 가진 Entity를 만들기에는 가볍고, 항목들이 정해져 있기 때문에 해당 방식이 효율적이라고 생각했음.
3. 검색
- 해당 부분도 고려해 아래 상세 필터링 부분도 제작했습니다. (Filter 중 handleMultiStringContentFilter 제작해 사용)
**3. JSON 삭제(추가 입력 정보를 자기소개로 변경)**
- options가 기획에서 사라져 제거하고, self_introduction(String) 을 추가했습니다.
기존 필터링 → 요청자와 완전 일치 여부를 기준으로 검색함.
새로운 필터링 → 요청자가 원하는 항목을 검색할 수 있음.
새로운 필터링은 Post 방식으로 Request Body에 json을 받아 사용할 수 있도록 하였습니다.
Key끼리는 AND …
> [COZY-264] 멤버 상세정보 기획 변경, 상세 필터링 검색 기능 구현, 멤버 상세정보 일치율 엔티티 분리 및 조회, 저장, 업데이트 방식 변경

- src/main/java/com/cozymate/cozymate_server/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/converter/ChatRoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/dto/ChatRoomResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/service/ChatRoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/service/ChatRoomQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/report/Report.java
- src/main/java/com/cozymate/cozymate_server/domain/report/ReportRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/report/controller/ReportController.java
- src/main/java/com/cozymate/cozymate_server/domain/report/converter/ReportConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/report/dto/ReportRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/report/enums/ReportReason.java
- src/main/java/com/cozymate/cozymate_server/domain/report/enums/ReportSource.java
- src/main/java/com/cozymate/cozymate_server/domain/report/repository/ReportRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/report/service/ReportCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- src/main/java/com/cozymate/cozymate_server/global/utils/EnumValid.java
- src/main/java/com/cozymate/cozymate_server/global/utils/EnumValidator.java
간단한 신고하기 기능 구현했습니다.
같은 사용자에게 같은 사유와 같은 신고 출처에 대한 신고는 중복 신고 처리했습니다.
RequestBody에서 enum에 대한 검증 어노테이션을 구현했습니다.
쪽지방 id 반환 API를 추가했습니다.
```java
public void saveReport(Member member, ReportRequestDto requestDto) {
checkReportSelf(member, requestDto.getReportedMemberId());
checkMemberExists(requestDto.getReportedMemberId());
checkDuplicateReport(member, requestDto);
Report report = ReportConverter.toEntity(member, requestDto);
reportRepository.save(report);
}
```
자신에 대한 신고인지 확인, 신고 대상 사용자가 존재하는지 확인, 중복된 신고 요청인지 확인 이후
신고 데이터 저장이 끝입니다~
```java
public class ReportRequestDto {
private Long reportedMemberId;
@EnumValid(enumClass = ReportSource.class)
private String reportSource;
@EnumValid(enumClass = ReportReason.class)
private String …
```
> [COZY-258] feat : 신고 API, 쪽지방id 반환 API

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/repository/MemberStatEqualityRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/service/MemberStatEqualityQueryService.java
멤버 상세정보 조회 시 방에 참여했는지 여부와 일치율을 추가했습니다.
한번 달아보겠습니다
잘 동작합니다.
방에 속해있지 않을 때 0을 리턴합니다.
감사합니다.
> [COZY-315] feat: 멤버 상세정보 조회 시 방에 참여했는지 여부와 일치율 조회 추가

- src/main/java/com/cozymate/cozymate_server/domain/friend/controller/FriendController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/Member.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/MemberStat.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/MemberStatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/querydsl/MemberStatQueryRepositoryImpl.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/service/MemberStatEqualityCommandService.java
멤버 상세정보 생성 수정 시 대학 정보(학교, 학과) 제외하고, 기숙사 미정 인원도 받을 수 있게 수정함
대학 연관관계 변경으로 관련 코드 수정
Friend Controller 전체 만료시켰습니다.
MemberStat 일부에서 빈칸이 가능하도록 변경했습니다.
..
역사 속에 남겨진 Friend...잘가
생성에서 잘 제외됨
수정에서 잘 제외됨
나머지 조회나 이런 부분은 한번씩 돌려보니 잘 돌아갔습니다.
감사합니다
> [COZY-292] feat: 멤버 상세정보 생성 수정 시 대학 정보(학교, 학과) 제외, 기숙사 미정 인원도 받을 수 있게 수정

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
방에 상세정보 1명일 때와 아예 없을 때 색깔 처리를 했습니다.
공개방일 때, 무조건 멤버 상세정보를 입력해야 하는 것으로 알고 있는데, 혹시 몰라 다 처리했습니다.
코멘트 달게요
다른 방에 들어가보지를 않아 테스트는 못했습니다. 다만 코드 보시면 납득이 되실 거 같습니다.
@suuu0719 확인 부탁드립니다. 늦어서 죄송해요ㅜㅜ
> [COZY-319] feat: 방에 상세정보 1명일 때와 아예 없을 때 색깔 처리

- src/main/java/com/cozymate/cozymate_server/domain/room/Room.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
공개방은 다른 사용자도 방 정보 조회 가능하게 수정
오타 및 필드 이름 수정
방정보 수정시 프로필 사진도 수정 가능하도록 변경했습니다
비공개방 조회시 해당방의 룸메이트인지 검사
공개방은 룸메이트 아니어도 방 정보 조회 가능
방 수정시 프로필 이미지도 수정되도록 변경
>
> [COZY-79] fix: 방 정보 조회 수정 및 방 수정사항에 프로필 사진 추가

- src/main/java/com/cozymate/cozymate_server/CozymateServerApplication.java
- src/main/java/com/cozymate/cozymate_server/global/config/AsyncConfig.java
- src/main/java/com/cozymate/cozymate_server/global/config/WebConfig.java
- src/main/java/com/cozymate/cozymate_server/global/logging/AopLogger.java
- src/main/java/com/cozymate/cozymate_server/global/logging/MdcCopyTaskDecorator.java
- src/main/java/com/cozymate/cozymate_server/global/logging/MdcLoggingInterceptor.java
- 로깅 세팅했습니다.
- 기존에 sql_format으로 되어있는게 서버에서 로그 체크하기에 불편함이 있어 false로 했습니다.
- 필요하신 분들은 config의 yml에서 true로 올리고 사용하시면 됩니다.
- request시 로그 출력하고
- 함수 호출시마다 호출 함수 출력하고
- response시에 로그 출력합니다.
- MDC를 사용했습니다.
[대충 개념만 확인하세용](https://dev-jwblog.tistory.com/126)
- AOP를 사용했습니다.
[얘도 대충 개념만 확인하세용](https://sharonprogress.tistory.com/195)
- 로그 제안사항 언제든 환영합니다
> [COZY-301] feat: 서버 디버깅용 1차 로깅 세팅

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/service/MemberStatEqualityQueryService.java
넵
멤버 일치율 조회시, 예외처리 수정 (exeception->null)
멤버 상세정보가 없는 사람이 멤버 상세정보가 있는 화면을 봤을 때, exception이 발생했었고, 이제 발생하지 않고 null을 리턴하도록 했습니다.
저걸 사용하는 API 2개 시험해봤습니다.
감사합니다.
> [COZY-360] feat: 멤버 일치율 조회시, 예외처리 수정

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/response/RoomDetailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
네
방장에게 보이는 방 참여 요청 목록 조회 추가했습니다
방 조회할때 기숙사 조회하는것도 같이 올릴게요
+사용자가 해당 방에 참여 요청을 했는지 여부 조회도 추가했습니다
방 참여 요청 목록 조회
방 조회 시 기숙사 정보 추가
사용자가 해당 방에 참여 요청을 했는지 여부 조회
참여요청중일때
참여요청중이 아닐때
> 고민사항도 적어주세요.
> [COZY-328] feat: 방장에게 보이는 방 참여 요청 목록 조회, 방 조회시 기숙사 정보 추가, 사용자가 해당 방에 참여 요청을 했는지 여부 조회

- src/main/java/com/cozymate/cozymate_server/domain/favorite/controller/FavoriteController.java
- src/main/java/com/cozymate/cozymate_server/domain/favorite/repository/FavoriteRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- 찜하기에서 예외 처리를 추가했습니다.
- 찜 목록 조회에서 member stat을 입력 안한 사용자가 찜 목록 조회 시 에러나던 부분 수정했습니다.
member stat 입력 안된 테스트용 계정으로 찜한 방 목록 조회 - 일치 수 전부 0 처리
member stat 입력 안된 테스트용 계정으로 찜한 사용자 목록 조회
member stat이 있는 계정으로 찜한 방 목록 조회 - 일치 수 조회 잘 됌
member stat이 있는 계정으로 찜한 사용자 목록 조회
member 2번이 1, 28, 29번 room을 찜한 상태
찜한 방 목록 조회시 전부 잘 조회됌
28번 방 -> disable로 변경, 29번 방 -> 인원 full로 변경 후에 찜한 방 목록 조회 시 - 1번 방만 조회됌
delete 쿼리 날라가고
db 확인
---
예외 처리 동작
member stat 없는 사용자를 찜하려는 경우
방 status가 disable인 방을 찜하려는 경우
인원이 가득 찬 방을 찜하려는 경우
비공개 방을 찜하려는 경우
> 고민사항도 적어주세요.
코드에 주석으로 코멘트 대체할게요
> [COZY-369] fix: 찜 하기, 목록 조회 로직 수정

- src/main/java/com/cozymate/cozymate_server/domain/member/repository/MemberRepository.java
네
사용자 검색 시 멤버 상세정보 없는 사람 제외
두줄 추가했습니다
수많은 테스트 계정중 있는거만 뜹니다
감사합니다
> [COZY-370] feat: 사용자 검색 시 멤버 상세정보 없는 사람 제외

- src/main/java/com/cozymate/cozymate_server/domain/mail/controller/MailController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomRecommendController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomRecommendConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/enums/RoomSortType.java
- src/main/java/com/cozymate/cozymate_server/domain/room/repository/RoomRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomRecommendService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/common/PageResponseDto.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
넵
- 방 추천 기능에 조회 타입이 총 3가지가 있습니다.
- 해당 조회 타입에 맞추어 기능을 추가했습니다.
- 또한 여러개가 필요할 경우 페이징 처리를 통해서 가져올 수 있도록 추가하였습니다.
최신 방 목록부터 불러오게 됩니다.
현재 반환되는 순서는 초대할 방, 좌심방, 우심방 순입니다.
아래부터 최근에 생성된 방임을 알 수 있습니다.
일치율 순으로 반환하게 됩니다.
해당 부분은 equality 값으로 높은 값이 먼저 반환됨을 알 수 있씁니다.
좌심방은 42퍼 일치율을 가집니다.
방이 가득 찰 때까지 인원이 적게 남은 순으로 반환하며, 동일한 반환값을 가질 때에는 equality가 높은 순으로 반환합니다.
우심방, 좌심방 초대할 방 순으로 반환되고 있습니다.
이렇게 인원이 1명, 2명, 3명 순으로 남은 것을 알 수 있습니다.
> 고민사항도 적어주세요.
> [COZY-368] feat: 방 추천 기능 Type에 따른 정렬 + Pagenation 처리 완료

- src/main/java/com/cozymate/cozymate_server/domain/fcm/controller/FcmController.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/enums/NotificationType.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- 방 초대 요청, 방 초대 수락/거절, 방 참여 요청, 방 참여 수락/거절 API에 푸시 알림 로직을 추가했습니다.
db에 저장 되면 푸시 알림 간게 보장된거라 이걸로 대체할게요
> 고민사항도 적어주세요.
테스트 한다고 알림 많이 가서 죄송합니다 ㅜ
> [COZY-382] feat: 방 초대 요청, 참여 요청, 수락/거절에 푸시 알림 로직 추가

- src/main/java/com/cozymate/cozymate_server/domain/favorite/repository/FavoriteRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/response/MemberStatDetailAndRoomIdAndEqualityResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
NE
MemberStat 조회시 초대 요청을 한 사용자인지, 찜을 했는지 여부 추가
눈꽃에 저희 방에 초대 요청을 보내고, 저를 찜하기도 했습니다.
말즈는 찜도 없고, 초대 요청도 하지 않았습니다.
테슽트 계정이 저희 방에 초대 요청을 보냈습니다
테슽트 계정이 포비를 조회하는 화면 : 정상
포비 입장에서 봤을 때 수락 거절을 선택할 수 있습니다.
음...멤버 상세정보 Service에서 room이나 mate에 접근하다보니까 지연시간이 좀 늘어나긴 하는데, 고민이네여
> [COZY-383] feat: MemberStat 조회시 초대 요청을 한 사용자인지, 찜을 했는지 여부 추가

- src/main/java/com/cozymate/cozymate_server/domain/mate/Mate.java
- src/main/java/com/cozymate/cozymate_server/domain/postcomment/PostCommentRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/postimage/PostImageRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/Room.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/request/PrivateRoomCreateRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/request/PublicRoomCreateRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/request/RoomUpdateRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
네 
방장이 나가는 경우 그 다음으로 가장 먼저 들어온 mate가 방장이 되도록 변경
비공개방 전환 API 구현
persona range 1-16으로 수정했습니다
방장이 나갔을 때
그 다음으로 들어온 mate가 방장이 됨
최후의 방장이 나갔을때 방 삭제되는 것 확인했습니다
**비공개방 전환**
이미 비공개방일때
비공개방 전환 성공
> 고민사항도 적어주세요.
> [COZY-395] feat: 방장 로직 수정, 비공개방 전환 API

- src/main/java/com/cozymate/cozymate_server/domain/mail/service/MailService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- src/main/resources/mail/mail_form.html
> [COZY-232] feat : mail template 생성

- src/main/java/com/cozymate/cozymate_server/domain/chat/repository/ChatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/service/ChatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/ChatRoom.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/converter/ChatRoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/dto/response/ChatRoomDetailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/dto/response/CountChatRoomsWithNewChatDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/service/ChatRoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/service/ChatRoomQueryService.java
- 쪽지방 목록 정렬
- 새로운 쪽지 유무 반환 추가
- 새로운 쪽지가 온 쪽지방 갯수 조회 API
- 회원탈퇴 쪽지 null 처리
마지막 쪽지방 읽은 시간 기준 이후에 쪽지가 온 경우 true를 반환
새 쪽지가 눈꽃에서만 왔기 때문에 새로운 쪽지방 갯수 조회 = 1
포비 계정으로 베로에게 쪽지 하나를 보낸 경우 - true반환, 최근 쪽지가 오고 간 순서대로 정렬됌
새로운 쪽지방 갯수 조회 = 2
쪽지방 목록 조회 시 탈퇴한 멤버 (알수없음)으로 처리 
탈퇴한 멤버와의 쪽지 상세 조회
> 고민사항도 적어주세요.
null 처리 최대한 한다고 했는데 오류 생기면 수정할게요
아직 쪽지방 삭제는 null 처리하고 테스트를 못해봤어요
> [COZY-400] feat: 쪽지방 목록 정렬 및 새로운 쪽지 유무 반환 추가, 새로운 쪽지 온 쪽지방 갯수 조회 API, 회원탈퇴 쪽지 null 처리

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
네
멤버 스탯 조회 시 초대 여부 조건 중 자신이 방장인 경우 검색할 때 조회 처리 실수가 있었습니다.
관련해서 핫픽스 햇습니다.
이제 잘 됩니다.
감사합니다.
> [COZY-414] fix: 멤버 스탯 조회 시 초대 여부 관련 에러 HOTFIX

- src/main/java/com/cozymate/cozymate_server/domain/fcm/dto/FcmPushTargetDto.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/RoomLog.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/converter/RoomLogConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/repository/RoomLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/Todo.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/repository/TodoRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/scheduler/NotificationScheduler.java
넵
- 기존에 Todo 변경으로 비활성화해둔 룸 로그를 활성화시켰습니다.
- 이를 위해서 룸로그에 mateId Long 값을 외래키 연관을 시키지 않고 추가했습니다 (mate와 연관해서 사용하지 않는 도메인이기 때문입니다.)
- Todo랑 RoomLog 연관도 그냥 없애버릴까 고민중입니다. 이것도 mate와 연관될 구석이 없고, 그냥 값을 찾기 위해서만 사용되기 때문입니다.
- 룸 로그와 함께 연관된 FCM도 다시 활성화시켰습니다.
- 코드 형태를 좀 리팩토링 했고, 기능이 크게 바뀐건 없지만 validation 체크가 좀 추가되었습니다.
- iOS에서 요청한 Todo 정렬 후 반환 기능을 또 추가하였습니다.
위의 데이터에서 조회한 결과입니다. 저는 mateId가 5번입니다.
``` json
"todoList": [
{
"todoId": 1245,
"content": "내 투두 테스트",
"completed": false,
"todoType": "self",
},
{
"todoId": 1250,
"content": "내꺼+1",
"completed": false,
"todoType": "self",
},
{
"todoId": 1247,
"content": "남 투두두두두",
"completed": false,
"todoType": …
```
> [COZY-340] feat: 투두에 룸 로그 활성화 및 기타 리팩터링

- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/response/MemberStatPreferenceDetailColorDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/response/MemberStatPreferenceResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/util/MemberStatUtil.java
네
룸메이트 추천, 필터링, 상세 필터링에 color를 넣어 리턴했습니다.
감사합니다다.
> [COZY-410] 룸메이트 추천, 필터링, 상세 필터링 color 리턴

- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/service/MemberStatEqualityCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/util/MemberStatEqualityUtil.java
네
멤버 스탯 업데이트 중 일치율 업데이트 관련해 NPE 가 발생했는데, 사실 비즈니스 로직 상 있을 수 없는 경우이지만 이럴 경우를 대비해 로직을 하나 만들어놨습니다.
- 
감사합니다.
> [COZY-417] 멤버 스탯이 없는 경우 자동 삭제하는 로직을 추가

- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberWithdrawService.java
Mate의 Status가 JOINED가 아닌대도 RoomCommandService.quitRoom()을 호출하는 경우에 문제가 생긴거 같습니다.
그래서 Mate의 Status가 JOINED인 경우에만 RoomCommandService.quitRoom()을 호출하도록 수정했습니다.
테스트 하기엔 품이 많이드는데 급한 부분이라.. 사고실험 해봤는데 이거 맞는거 같아요
코드도 딸랑 한줄 추가 했어여
> 고민사항도 적어주세요.
> [COZY-421] fix : mate 삭제전 방나가기 EntryStatus.equals(JOINED)인 경우에만 나가는걸로 수정

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/MemberStatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/RoomLog.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/converter/RoomLogConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/repository/RoomLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/Rule.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/dto/request/CreateRuleRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/repository/TodoRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
넵
- 롤 삭제시 투두가 삭제됩니다.
- 투두가 삭제될 시 룸 로그의 할당된 값이 사라집니다.
- 패스패스패스
> 고민사항도 적어주세요.
> [COZY-408] fix: 롤 삭제시 투두 삭제되도록 수정

- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
네 
사용자가 초대받은 방인지 조회, 방장이 방에 참여 요청한 사용자인지 조회하는 API 추가했습니다
**사용자가 초대받은 방인지 조회**
초대 받았을 때
초대 안받았을 때
**방장이 방에 참여 요청한 사용자인지 memberId로 조회**
방장 아닐때
참여 요청 보낸 사용자일때
참여 요청 보낸  사용자 아닐 때
> 고민사항도 적어주세요.
> [COZY-427] feat: 사용자가 초대받은 방인지 조회, 방장이 방에 참여 요청한 사용자인지 조회하는 API 추가

- src/main/java/com/cozymate/cozymate_server/domain/mate/Mate.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
> [COZY-432] hotfix: isExit 삭제

- src/main/java/com/cozymate/cozymate_server/domain/auth/enums/TokenType.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/userdetails/AdminDetails.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtFilter.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtUtil.java
- src/main/java/com/cozymate/cozymate_server/global/config/SecurityConfig.java
- src/main/java/com/cozymate/cozymate_server/global/utils/SwaggerFilter.java
스웨거 ui 접근전 파라미터에 key를 넣고 key 검증에 성공하면 브라우저 쿠키에 토큰을 넣어줍니다.
> 고민사항도 적어주세요.
> [COZY-438] feat : 스웨거 ui 접근전 파라미터에 key를 넣고 key 검증에 성공하면 브라우저 쿠키에 토큰을 넣어줍니다.

- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtUtil.java
- src/main/java/com/cozymate/cozymate_server/global/utils/SwaggerFilter.java
> [COZY-438] fix : 토큰 만료시간 분리 및 관리자 토큰 발급 관련 오류 수정

- src/main/java/com/cozymate/cozymate_server/domain/favorite/dto/response/PreferenceMatchCountDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
네
1. 멤버 스탯 없는 사용자가 다른 사용자를 찜하는 것 허용
2. 멤버 스탯 없는 사용자가 찜한 사용자 목록 조회하는 경우 로직 추가
3. 멤버 스탯 없는 사용자가 찜한 방 조회할 때 count 값을 0 말고 null로 반환
멤버 스탯 없는 테스트 계정으로 사용자 찜하기
찜한 사용자 목록 조회 결과
찜한 방 목록 조회 결과
> 고민사항도 적어주세요.
> [COZY-441] fix: 멤버 스탯 없는 사용자에 대한 찜 수정

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
예
어떤 방에 들어가는 순간 기존 초대 및 참여 요청을 자동으로 날립니다
memberId 99 → 여러방(57,72,37)에 INVITED, PENDING 상태
방장에게 보이는 참여요청 리스트
99번 참여 요청 수락함
37번 JOINED 룸 제외하고 모든 요청 지워짐
98번 요청을 거절했을때는 안날라감
> 고민사항도 적어주세요.
> [COZY-432] feat: 사용자가 방에 들어가면 다른 요청들 날리기

- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomRecommendConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/response/RoomRecommendationResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomRecommendService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/util/RoomStatUtil.java
- src/main/java/com/cozymate/cozymate_server/global/utils/RoomStatUtil.java
1. 방 일치율 계산 메서드, 칩 일치수 계산 메서드를 RoomStatUtil 클래스로 분리했습니다
2. RoomQueryService, RoomRecommendService, FavoriteQueryService에 적용했습니다
3. 성능 개선을 위해 페치조인 사용하도록 일부 수정했습니다
수정 전 방 추천 조회
수정 후 방 추천 조회 - 칩 일치수 반환 형태가 좀 수정되었습니다
---
찜한 방 조회
---
RoomQueryService에서 4개? RoomStatUtil로 변경되었는데 그 중 한개 테스트
일치율 잘 나옵니다
> 고민사항도 적어주세요.
@eple0329 @suuu0719 두 분 코드 조금 수정해서 확인해주세요~
> [COZY-445] refac: RoomStatUtil 분리 및 적용

- src/main/java/com/cozymate/cozymate_server/domain/mail/service/MailService.java
네
메일 인증 시 혼동 문자 `IlOo0` 을 제외하고 코드를 생성합니다.
이게 다에요 진짜
> 고민사항도 적어주세요.
> [COZY-448] fix : 메일 인증 시 혼동 문자 제거

- src/main/java/com/cozymate/cozymate_server/domain/chat/service/ChatCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/converter/ChatRoomConverter.java
네
- 쪽지 내용 앞뒤 공백 trim 처리
수정 전 쪽지방 목록 조회
수정 후 쪽지방 목록 조회
---
쪽지 작성 시
db 저장 상태 - trim 처리
> 고민사항도 적어주세요.
> [COZY-449] fix: 쪽지 내용 앞뒤 공백 trim 처리

- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtFilter.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberWithdrawService.java
- src/main/java/com/cozymate/cozymate_server/domain/role/repository/RoleRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/repository/RoomLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/repository/RuleRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/repository/TodoRepository.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
빈방인 경우 방을 삭제하는 로직을 수정했습니다.
- roomlog-> todo -> role -> mate -> rule 순서
- 삭제할때 쿼리를 하나씩 날리지 않도록 벌크연산으로 수정했습니다.
- 탈퇴한 사용자의 토큰이 유효합니다.(access token 은 저장 안함)
- 토큰으로 탈퇴한 사용자를 load하면 권한 배열이 비어있기 때문에 권한이 비어있는 경우에 대해 예외를 처리했습니다.
> 이미 탈퇴를 시켜버려서.. 디비보면 저랑 델로가 없을거에여 리뷰한 사이에 생겼을지도..?
> 고민사항도 적어주세요.
> [COZY-460] fix : 탈퇴시 -> 방 나가기 -> 빈 방인 경우 삭제 로직 수정 

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
네
기존에 Todo 완료시 FCM이 제대로 전송되지 않는 에러가 있엇는데, 해당 에러를 해결했습니다.
아래의 에러가 발생했습니다.
해당 원인은 Mate를 가져올 때 Member를 지연 로딩을 통해 가져와야하는데, 가져오지 못하는 문제였고,
Fetch join을 사용하여 해결했습니다.
아래처럼 수정이 완료되었습니다.
> 고민사항도 적어주세요.
> [COZY-467] fix: Todo 완료시 알림 전송 에러 해결

- .github/workflows/pr_review_reminder.yml
네
PR 리마인더 깃허브 액션에서, 스케줄러는 정상 동작했지만, invalid json 문제로 인해 전송이 되지 않는 문제가 있어 해결했습니다.
> 고민사항도 적어주세요.
> [COZY-478] fix: 깃허브 액션 에러 해결

- .github/workflows/pr_review_reminder.yml
넵
리마인더 길이 초과로 인해 디스코드로 전송되지 않은 이슈 해결했습니다.
리뷰 데이터를 PR에서 가져오다가, 코드 수정으로 사용하지 않는것을 확인하여 제거했습니다.
CodeRabbit이 너무 시끄럽게 떠들어서 발생했습니다.
> 고민사항도 적어주세요.
워크플로우 수정이니 바로 머지하겠습니다.
> [COZY-485] fix: 리뷰 리마인더 ENV 길이 초과 에러 해결
