- .github/workflows/build_and_deploy.yml
- Dockerfile
- build.gradle
- src/main/java/com/cozymate/cozymate_server/global/config/SshDataSourceConfig.java
> [COZY-6] feat: CI/CD 세팅

- .github/workflows/build_and_deploy.yml
> [COZY-6] feat: Staging 서버의 CI/CD 완료

- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- 단순 오탈자로 발생한 실행 에러 해결입니다.
- 따로 리뷰 없이 머지 하겠습니다.
```java
```
>
> [COZY-138] PR Merge 후 실행 에러 해결

- src/main/java/com/cozymate/cozymate_server/domain/todo/Todo.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/controller/TodoController.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/converter/TodoConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/dto/TodoRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/dto/TodoResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/repository/TodoRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoQueryService.java
- 참가한 방{roomId}에
- 특정 일자(timePoint)별 
- 룸메마다의 To-Do 조회 기능입니다.
- 간단하니 간단설명 진행합니다.
- timePoint 값을 받는데, 2024-07-30의 형식으로 받습니다.
- 만약 timePoint가 입력되지 않는다면, 오늘 날짜를 넣게 됩니다. (required=false)
``` java
@GetMapping("/{roomId}")
@Operation(
summary = "[무빗] 특정 방의 특정 날짜 기준 룸메별 To-Do 조회",
description = "본인이 참가한 방에서만 조회가 가능합니다. | timePoint를 지정하지 않으면 오늘 날짜 기준으로 반환합니다.")
public ResponseEntity<ApiResponse<TodoListResponseDto>> getTodo(
@PathVariable Long roomId,
@RequestParam Long memberId,
@RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate timePoint
) {
if (timePoint == null) {
timePoint = LocalDate.now();
}
TodoListResponseDto todoListResponseDto = todoQueryService.getTodo(roomId, memberId,
timePoint);
return ResponseEntity.ok(
ApiResponse.onSuccess(todoListResponseDto));
} …
```
> [COZY-25] 참가한 방의 특정 일자별 Todo 목록 조회 기능 구현

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomCreateResponse.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
생성한 방의 정보(방 초대 정보)를 조회하는 기능입니다.
```java
@GetMapping("/{id}")
@Operation(summary = "[바니] 생성한 방 정보 조회 기능", description = "방 아이디를 입력합니다.")
public ResponseEntity<ApiResponse<RoomCreateResponse>> getRoom(@PathVariable Long id) {
RoomCreateResponse response = roomCommandService.getRoomById(id);
return ResponseEntity.status(SuccessStatus._OK.getHttpStatus())
.body(ApiResponse.onSuccess(response));
}
```
PathVariable에 방id를 입력하면 해당 방의 초대정보를 조회합니다.
```java
// RoomCreateResponse.java
@Getter
@AllArgsConstructor
public class RoomCreateResponse {
private String name;
private String inviteCode;
private Integer profileImage;
}
```
RoomCreateResponse dto를 이용해 방이름, 프로필이미지, 초대코드 정보가 반환되도록 하였습니다.
```java
// RoomQueryService.java
@Service
@RequiredArgsConstructor
public class RoomQueryService {
private final …
```
> [COZY-79] 생성한 방 정보 조회 API

- src/main/java/com/cozymate/cozymate_server/domain/friend/service/FriendQueryService.java
> [COZY-61] fix: memberrepository 경로 변경

- src/main/java/com/cozymate/cozymate_server/domain/friend/Friend.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/FriendRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/controller/FriendController.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/converter/FriendConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/dto/FriendResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/service/FriendCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/service/FriendQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
기능은 친구 찜하기, 찜 해제하기, 찜 포함해서 조회하기인데,
API 1개 추가하고 친구 목록 조회하는 API 수정했습니다.
사옹하게 Converter 사용을 잘못한 것 같아서 그 부분은 Refactor 했습니다.
```java
private Boolean likesReceiver = Boolean.FALSE;
private Boolean likesSender = Boolean.FALSE;
//중간 관련 없는 코드
public void toggleLikesReceiver() {
this.likesReceiver = !this.likesReceiver;
}
public void toggleLikesSender() {
this.likesSender = !this.likesSender;
}
```
likesReceiver - Sender가 Receiver를 좋아하는지 여부
likesSender - Receiver가 Sender을 좋아하는지 여부
```java
@PutMapping("/toggle-like/{memberId}")
public ResponseEntity<ApiResponse<FriendLikeResponseDTO>> likeFriendRequest(
@PathVariable Long memberId,
@RequestBody @Valid FriendRequestDTO sendFriendRequestDTO) {
return ResponseEntity.ok(
ApiResponse.onSuccess(
friendCommandService.toggleLikeFriend(memberId, …
```
> [COZY-155] 친구 찜하기, 찜 해제하기, 찜 포함해서 조회하기

- src/main/java/com/cozymate/cozymate_server/domain/auth/controller/KakaoController.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/controller/SocialLoginController.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/dto/AuthResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/service/AuthService.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/AuthConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtFilter.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/converter/MemberConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/MemberResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
TokenResponse 통일했습니다.
토큰 발급시 Response Body 수정했습니다.
```java
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class TokenResponseDTO {
String message;
String refreshToken;
MemberResponseDTO.MemberInfoDTO memberInfoDTO;
}
```
```java
public class MemberResponseDTO {
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public static class MemberInfoDTO {
private String name;
private String nickname;
private String gender;
private String birthday;
private Integer persona;
}
}
```
responseBody 확인
```json
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"message": "임시 토큰 발급 완료",
"refreshToken": "3642806182:KAKAO",
"memberInfoDTO": {
"name": "",
"nickname": "",
"gender": "", …
```
> [COZY-161] TokenResponse 통일

- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/RuleRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/repository/RuleRepository.java
> [COZY-35] hotfix: Repository 에러 해결

- src/main/java/com/cozymate/cozymate_server/domain/auth/controller/KakaoController.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/controller/SocialLoginController.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/dto/AuthResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/service/AuthService.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/AuthConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtFilter.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/converter/MemberConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/MemberResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/config/SecurityConfig.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> [COZY-161] Hotfix/cozy 161.2

- src/main/java/com/cozymate/cozymate_server/domain/auth/service/AuthService.java
- ㅎㅎ 자기전에 한번 테스트
```java
```
>
> [COZY-161] hotfix: header 반환 형식 수정

- src/main/java/com/cozymate/cozymate_server/domain/friend/controller/FriendController.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/service/FriendCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/friend/service/FriendQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
[COZY-164] feat: friend에서 자신에게 요청을 보내는 경우 제외하기
만든 기능 토큰과 연결하기
그리고 바니가 잡아준 같은 사람에게 친구 요청을 보냈을 때 예외처리도 완료했습니다.
아래 동작에 토큰을 연결했습니다.
```java
memberDetails.getMember()
```
위 코드로  Member를 가져왔습니다.
```java
// 요청하는 사람과 수락하는 사람이 같은지 검사
if(sender.getId().equals(receiver.getId())){
throw new GeneralException((ErrorStatus._FRIEND_REQUEST_EQUAL));
}
```
모든 기능에 대해서 테스트 완료 했습니다.
말즈의 가이드를 보고 토큰을 생성하고 유저 정보를 추가했습니다.
사용자 정보 토큰으로 Member를 받아 추가 완료
사용자 정보 토큰으로 Member 수정 완료
제가 INFP->ENFP로 바뀌었습니다.
친구 관련 API 테스트 완료 (말즈 <-> 포비)
> 자유롭게 해주세요!!
[COZY-164]: https://cozymate.atlassian.net/browse/COZY-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [COZY-164] 만든 기능 토큰과 연결하기

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/querydsl/MemberStatQueryRepositoryImpl.java
일치율 계산 시 같은 학교, 같은 성별 조건을 빼먹어서 추가했습니다.
(바로잡아준 말즈에게 감사를..)
```java
@Override
public List<MemberStat> getFilteredMemberStat(List<String> filterList, MemberStat criteriaMemberStat) {
JPAQuery<MemberStat> baseQuery = queryFactory.selectFrom(memberStat);
BooleanBuilder builder = new BooleanBuilder();
//criteriaMemberStat은 제외하기
builder.and(memberStat.id.ne(criteriaMemberStat.getId()));
//성별이 틀리면 제외
builder.and(member.gender.eq(criteriaMemberStat.getMember().getGender()));
// 대학이 틀리면 제외
builder.and(memberStat.university.id.eq(criteriaMemberStat.getUniversity().getId()));
if (filterList != null) {
filterList.forEach(filter -> applyFilter(builder, filter, criteriaMemberStat));
}
return baseQuery
.join(memberStat.member, member)
.where(builder)
.fetch();
}
```
제외 조건을 두개 추가하고, Member와 조인해 비교했습니다. …
> [COZY-169] 일치율 계산 시 같은 학교, 같은 성별로 필터링하기

- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> [COZY-173] hotfix : 회원가입시 clientId 중복 검증

- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> [COZY-173] 긴급수정 : 닉네임 검증 로직 수정

- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> [COZY-173] 긴급 수정 : 닉네임 중복 검증 로직 수정 , submodule update

- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomCreateResponse.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
> [COZY-77] 방 생성 리턴값 수정

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/global/utils/TimeUtil.java
MemberStat을 가져올 때 Response를 변경했습니다.
기존 : 시간만 Reponse
변경점  : 오전 오후, 시간을 나눠서 줌
```java
public static String convertToMeridian(Integer time){
if(time < HALFDAY){
return MORNING;
} else if(time.equals(HALFDAY)){
return AFTERNOON;
}
return AFTERNOON;
}
public static Integer convertToTime(Integer time){
if(time.equals(STARTDAY)){
return HALFDAY;
}
else if(time <= HALFDAY){
return time;
}
return time - HALFDAY;
}
```
오전 오후로 바꾸는 Util 하나와,
시간으로 바꿔주는 Util 하나를 만들었습니다.
```java
.wakeUpMeridian(TimeUtil.convertToMeridian(memberStat.getWakeUpTime()))
.wakeUpTime(TimeUtil.convertToTime(memberStat.getWakeUpTime()))
.sleepingMeridian(TimeUtil.convertToMeridian(memberStat.getSleepingTime()))
.sleepingTime(TimeUtil.convertToTime(memberStat.getSleepingTime())) …
```
> [COZY-178] MemberStat ResponseType 번경

- src/main/java/com/cozymate/cozymate_server/domain/post/controller/PostController.java
- src/main/java/com/cozymate/cozymate_server/domain/post/converter/PostConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/post/dto/PostDetailDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/post/dto/PostDetailViewDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/post/dto/PostSummaryDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/post/service/PostQueryService.java
Post 관련 Response를 받는 과정에서 통일이 안된 부분과 부족한 정보가 있어 추가했습니다.
제가 IOS 작업하는데 API 수정해야해서 바로 Merge하겠습니다!
PostDetailViewDTO.java -> PostDetailDTO.java
```java
// 기존 코드
private List<String> postImageList;
// 수정한 코드
private List<String> imageList;
```
```java
//추가한 코드
private LocalDateTime createdAt;
```
> 감사합니다
> [COZY-179] Post 관련 Response 통일을 위해 Refactoring

- src/main/java/com/cozymate/cozymate_server/domain/auth/service/AuthService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> [COZY-173] fix : 로그인 시 리프레시토큰 발급 로직 수정

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomExistResponse.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
코지홈 활성화 화면을 위한 조건 확인입니다.
현재 참여중인 방이 있다면 참여중인 roomId를, 없다면 roomId값을 0으로 리턴합니다.
그리고 생성된 방의 정보 (방이름, 프로필, 초대코드)는 방장만이 아니라 룸메이트라면 모두 조회할 수 있도록 수정하였습니다
WAITING 또는 ENABLE 상태인 방에 JOIN중일때만 해당 roomId를 리턴합니다
이외의 경우는 모두 roomId값이 0으로 리턴됩니다
```java
@GetMapping("/exist")
@Operation(summary = "[바니] 사용자가 참여한 방이 있는지 여부 조회", description = "현재 참여중인 방이 있다면 해당 roomId가, 없다면 roomId값이 0으로 리턴됩니다.")
@SwaggerApiError({
ErrorStatus._MEMBER_NOT_FOUND
})
public ResponseEntity<ApiResponse<RoomExistResponse>> getExistRoom(@AuthenticationPrincipal MemberDetails memberDetails) {
RoomExistResponse response = roomQueryService.getExistRoom(memberDetails.getMember().getId());
return ResponseEntity.ok(ApiResponse.onSuccess(response));
}
```
```java
public RoomExistResponse getExistRoom(Long memberId) { …
```
> [COZY-184] 사용자가 참여한 방이 있는지 여부 조회, 방정보 조회 권한 수정

- src/main/java/com/cozymate/cozymate_server/domain/role/converter/RoleConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/RoleResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleQueryService.java
- todo와 동일합니다. 바로 머지할게용
```java
```
>
> [COZY-187] refacor: Role 반환 형식에 Persona 추가

- src/main/java/com/cozymate/cozymate_server/domain/roomlog/RoomLog.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/converter/RoomLogConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/repository/RoomLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
- Todo의 상태가 변경되었을 때 Room Log를 추가하는 기능을 구현했습니다.
- 다른 부분에서도 Room Log를 추가해야하지만, 해당 부분은 제 영역과 좀 벗어나있어 이후에 해당 파트 담당자와 협의 후 진행하겠습니다.
- Todo 상태 변경시 호출되는 함수입니다.
- 모든걸 상수로 바꿔버리고 싶었는데, 한계가 보여 이렇게 했고, 새로운 방법을 찾는다변 변경할 예정입니다.
```java
@Service
@RequiredArgsConstructor
@Transactional
public class RoomLogCommandService {
private final RoomLogRepository roomLogRepository;
private static final String DEFAULT_FINAL_MESSAGE = "완료했어요!";
private static final List<String> FINISH_MESSAGE_LIST = Arrays.asList(
"완료하여, cozy room을 만드는데 기여했어요!",
"완료했어요! 얼른 칭찬해주세요!",
"완료하여, 최고의 cozy mate가 되었어요!"
);
public void addRoomLogFromTodo(Todo todo) {
Optional<RoomLog> existingLog = roomLogRepository.findByTodoId(todo.getId());
// False일 때 기존 로그 삭제, True일 때 새로운 로그 생성
if (Boolean.FALSE.equals(todo.isCompleted()) && …
```
> [COZY-188] feat: Todo 완료시 Room Log 추가 기능 구현

- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoQueryService.java
> [COZY-197] refac: 이름 반환 -> 닉네임 반환으로 변경

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoQueryService.java
> [COZY-204] feat: PENDING인 사람은 안가져오도록 수정

- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogCommandService.java
> [COZY-190] feat: 방 생성 API 호출 시 방 로그 추가

- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogCommandService.java
> [COZY-205] feat: RoomLog에서 name을 반환하는 것을 nickname으로 변경

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/scheduler/NotificationScheduler.java
> [COZY-206] feat: 이벤트로 특정 시간에 완료되지 않은 Role RoomLog에 추가, 생일, BestCozymate 기능 Roomlog 추가

- src/main/java/com/cozymate/cozymate_server/domain/role/enums/DayListBitmask.java
- src/main/java/com/cozymate/cozymate_server/domain/role/repository/RoleRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/repository/RuleRepository.java
- src/main/java/com/cozymate/cozymate_server/global/scheduler/NotificationScheduler.java
> [COZY-206] feat: 매일 자정 Todo 생성되는 Schedular 추가

- src/main/java/com/cozymate/cozymate_server/domain/member/converter/MemberConverter.java
> [hotfix] : 모든 사용자를 남성화

- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
> [COZY-209] feat: 오늘 Role을 생성했다면 Todo도 추가

- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/ClientIdMaker.java
- src/main/java/com/cozymate/cozymate_server/domain/member/converter/MemberConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/member/enums/SocialType.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
> [COZY-211] Feat : 시연용 로그인 구현

- src/main/java/com/cozymate/cozymate_server/domain/fcm/dto/FcmPushTargetDto.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/FcmPushService.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/controller/NotificationLogController.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/enums/NotificationType.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/repository/TodoRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/event/EventListener.java
FCM 이사해서 submodule 수정함
오늘 할 TODO를 완료하면 FCM 알림
베로 부탁해!!!!!
```java
```
부탁...
> 데모데이 때 필요해서 선 머지하겠슴다.
> [COZY-216] TODO 완료시 FCM 알림 구현

- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomCreateRequest.java
> [COZY-218] feat: 방 생성시 이름 중간 공백 허용

- src/main/java/com/cozymate/cozymate_server/domain/post/service/PostQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/postcomment/PostCommentRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/postcomment/service/PostCommentQueryService.java
> [COZY-223] fix : 댓글 desc 삭제

- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
> [COZY-81] fix: 방 참여 설명 수정

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/util/MemberUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/enums/NotificationType.java
- src/main/java/com/cozymate/cozymate_server/global/scheduler/NotificationScheduler.java
> [COZY-226] feat: 스케줄러 수정, NotificationLog에 이름 형식 수정

- src/main/java/com/cozymate/cozymate_server/domain/fcm/converter/FcmConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/FcmCommandService.java
> [COZY-227] fix : deviceId 값 -> clientId값으로 임시 변경

- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/controller/NotificationLogController.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/repository/NotificationLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/service/NotificationLogQueryService.java
- src/test/java/com/cozymate/cozymate_server/domain/notificationlog/service/NotificationLogQueryServiceTest.java
> [COZY-228] feat: NotificationLog 반환순서 최신순으로 변경

- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/converter/NotificationLogConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/dto/NotificationLogResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/service/NotificationLogQueryService.java
> [COZY-230] feat: 카테고리 반환 추가

- src/main/java/com/cozymate/cozymate_server/domain/chat/dto/ChatRequestDto.java
> [COZY-229] fix : 오류 수정

- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/FcmPushService.java
> [COZY-234] fix : 어노테이션 누락 추가

- src/main/java/com/cozymate/cozymate_server/domain/chat/controller/ChatController.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/converter/ChatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/dto/ChatResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/service/ChatQueryService.java
- src/test/java/com/cozymate/cozymate_server/domain/chat/service/ChatQueryServiceTest.java
> [COZY-235] fix : 반환값 추가 및 응답 형식 수정

- src/main/java/com/cozymate/cozymate_server/domain/chat/controller/ChatController.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/converter/ChatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/dto/ChatResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/service/ChatCommandService.java
> [COZY-235] fix : 쪽지 작성 성공 시 chatRoomId 반환

- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/FcmPushService.java
> [COZY-235] fix : Message에 Notification 추가

- src/main/java/com/cozymate/cozymate_server/domain/fcm/dto/FcmPushContentResultDto.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/FcmPushService.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/enums/NotificationType.java
- src/test/java/com/cozymate/cozymate_server/domain/fcm/service/FcmCommandServiceTest.java
- src/test/java/com/cozymate/cozymate_server/domain/fcm/service/FcmPushServiceTest.java
- src/test/java/com/cozymate/cozymate_server/domain/notificationlog/NotificationLogTestBuilder.java
- src/test/java/com/cozymate/cozymate_server/domain/notificationlog/service/NotificationLogQueryServiceTest.java
> [COZY-235] fix : 알림 로그와 푸시 알림 내용 구분 생성, 테스트 코드 주석 처리

- .github/workflows/pr_review_bot.yml
> [COZY-243] feat: Github Token 기본값 사용

- .github/workflows/pr_review_bot.yml
> [COZY-243] feat: PR 리뷰봇 버전 업

- src/main/java/com/cozymate/cozymate_server/domain/todo/Todo.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/controller/TodoController.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/dto/TodoRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
- 간단하게 투두 수정기능 구현했습니다.
아래 서비스 코드만 보시면 됩니다.
```java
public void updateTodoContent(
Member member,
UpdateTodoContentRequestDto requestDto
) {
Todo todo = todoRepository.findById(requestDto.getTodoId())
.orElseThrow(() -> new GeneralException(ErrorStatus._TODO_NOT_FOUND)); // 수정할 투두가 존재해야함
if(todo.getRole() != null){
throw new GeneralException(ErrorStatus._TODO_NOT_VALID); // 투두가 롤에서 만들어진 것이라면 수정 불가
}
if (Boolean.FALSE.equals(todo.getMate().getMember().getId().equals(member.getId()))) {
throw new GeneralException(ErrorStatus._TODO_NOT_VALID); // 투두가 본인이 만든게 아니라면 수정 불가
}
todo.updateContent(requestDto.getContent(), requestDto.getTimePoint()); // 투두 수정
todoRepository.save(todo);
}
```
위의 코드의 주석처럼 동작하며, content timepoint는 선택값으로 둘 중 하나만 입력되면 해당 값만 수정됩니다.
위의 투두가 있습니다.
29일에 집에가는 투두로 수정하고자 합니다.
29일에 …
> [COZY-28] feat: Todo 수정기능 구현

- .github/workflows/pr_review_bot.yml
> [COZY-243] feat: PR 리뷰봇 버전업

- .github/workflows/pr_review_bot.yml
> [COZY-243] feat: 프롬프트 수정

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/role/Role.java
- src/main/java/com/cozymate/cozymate_server/domain/role/controller/RoleController.java
- src/main/java/com/cozymate/cozymate_server/domain/role/converter/RoleConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/RoleRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/RoleResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleQueryService.java
1. 주석 추가 등 리팩토링을 진행했습니다.
2. 수정 기능을 추가했습니다.
3. 변경된 로직에 맞춰서 기능을 좀 수정했습니다
이 코드 변경 사항에는 MateRepository, Role, RoleController, RoleCommandService, RoleQueryService 등을 포함하여 여러 클래스에서 수정이 이루어졌습니다. 주요 변경 사항을 요약하면 다음과 같습니다.
1. MateRepository.java
•	새로운 메서드 findByIdIn(List<Long> memberIdList)가 추가되었습니다.
•	이 메서드는 주어진 memberIdList에 포함된 ID들을 가진 Mate 엔티티를 조회하는 메서드입니다.
2. Role.java
•	updateEntity 메서드가 추가되었습니다.
•	이 메서드는 Role의 content와 repeatDays 필드를 업데이트합니다.
•	content는 null이 아닐 때만 업데이트되고, repeatDays는 -1이 아닌 값만 업데이트합니다. -1은 null 입력을 의미하는 특별한 값으로 취급합니다.
3. RoleController.java
•	REST API 경로 및 메서드 추가:
•	@RequestMapping("/rooms")로 변경되었습니다. Role과 Room이 연결된 API 경로로 더 직관적입니다.
•	/rooms/{roomId}/roles 경로에 대한 새로운 메서드들:
•	createRole: 특정 방(Room)에 Role을 생성하는 POST 메서드가 추가되었습니다.
•	getRoleList: 특정 방의 Role 목록을 조회하는 GET 메서드가 …
> [COZY-33] feat: 리팩토링, 수정 기능 추가

- src/main/java/com/cozymate/cozymate_server/domain/chat/controller/ChatController.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/service/ChatCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/chat/service/ChatQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/converter/ChatRoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/dto/ChatRoomResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/service/ChatRoomQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/controller/MemberBlockController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/repository/MemberBlockRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/service/MemberBlockCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberblock/util/MemberBlockUtil.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
1. 입력 파라미터의 리스트에서 차단한 사용자를 필터링하는 메서드를 구현했습니다.
2. 특정 사용자가 로그인한 사용자에 의해 차단되었는지 확인하는 메서드를 구현했습니다.
3. Chat, ChatRoom 도메인에 적용했습니다.
```java
//MemberBlockUtil.java
public <T> List<T> filterBlockedMember(List<T> targetList, Member member,
Function<T, Long> idExtractor) {
// 1
Set<Long> blockedMemberIds = getBlockedMemberIds(member);
// 2
if (blockedMemberIds.isEmpty()) {
return targetList;
}
// 3
return filterByBlockedIds(targetList, blockedMemberIds, idExtractor);
}
private Set<Long> getBlockedMemberIds(Member member) {
return memberBlockRepository.findBlockedMemberIdsByMember(member);
}
// 3
private <T> List<T> filterByBlockedIds(List<T> targetList, Set<Long> blockedIds,
Function<T, Long> idExtractor) {
return targetList.stream() …
```
> [COZY-263] feat : 차단된 사용자 필터링을 위한 유틸성 메서드 구현

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/university/University.java
- src/main/java/com/cozymate/cozymate_server/domain/university/UniversityRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/university/controller/UniversityController.java
- src/main/java/com/cozymate/cozymate_server/domain/university/converter/UniversityConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/university/dto/UniversityRequest.java
- src/main/java/com/cozymate/cozymate_server/domain/university/dto/UniversityResponse.java
- src/main/java/com/cozymate/cozymate_server/domain/university/repository/UniversityRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/university/service/UniversityService.java
대학교 정보 CRUD API 입니다.
수정/생성 API는 AWS 람다로 이전 될 예정입니다.
혹시 유지된다면 admin 만 접근할 수 있게 수정하겠습니다~
```java
public class UniversityService {
private final UniversityRepository universityRepository;
@Transactional
public UniversityResponse.UniversityDTO createUniversity(UniversityRequest.UniversityDTO requestDTO) {
University university = UniversityConverter.toUniversity(requestDTO);
universityRepository.save(university);
return UniversityConverter.toUniversityDTO(university);
}
@Transactional
public UniversityResponse.UniversityDTO updateUniversity(UniversityRequest.UniversityDTO requestDTO) {
University university = universityRepository.findByName(requestDTO.getName())
.orElseThrow(() -> new GeneralException(ErrorStatus._UNIVERSITY_NOT_FOUND));
university.update(requestDTO.getMailPattern(), …
```
> [COZY-280] 대학교 관련 API 추가

- src/main/java/com/cozymate/cozymate_server/global/utils/ImageUtil.java
- 매우 간단.
- 그냥 값만 바꿨습니다.
- CDN 적용하게 되면서, baseuri 주소를 변경하게 되었습니다.
- 
```java
```
잘 됩니당
>
> [COZY-302] feat: CDN 주소 변경 및 Post에서 반환하는 이미지 uri 수정

- src/main/java/com/cozymate/cozymate_server/domain/member/Member.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/MemberStat.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/MemberStatPreference.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/controller/MemberStatPreferenceController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/dto/MemberStatPreferenceDto.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/repository/MemberStatPreferenceRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/service/MemberStatPreferenceCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/service/MemberStatPreferenceQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/util/MemberStatPreferenceUtil.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
멤버가 선호항목 4가지를 고를 수 있게 CRU를 구현했습니다.
```java
//MemberStatPreference.java
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
// TODO: 연관관계를 설정할지 말지 생각해보자
@OneToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "member_id", referencedColumnName = "id")
private Member member;
private String selectedPreferences;
public void update(String newPreferences){
this.selectedPreferences = newPreferences;
}
```
위처럼 String으로 저장했습니다. DTO 선에서 무조건 4개 항목이 들어가게 Valid 했습니다.
정말 간단하고, 중간에 존재하는 항목을 줬는지 Util에서 검사하기만 했습니다.
설명이 없어도 이해가 가능할 정도의 코드입니다.
```java
private static final Set<String> validPreferences = new HashSet<>(Arrays.asList(
"admissionYear", "numOfRoommate", "acceptance", "wakeUpTime",
"sleepingTime", "turnOffTime", "smokingState", "sleepingHabit",
"airConditioningIntensity", …
```
> [COZY-312] feat: 멤버 선호 항목 4가지 CRU 구현

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatDifferenceResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/enums/DifferenceStatus.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/util/MemberStatUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/controller/MemberStatPreferenceController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/room/enums/DifferenceStatus.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
방 라이프스타일 일치 칩들을 리턴하는 DTO, Util을 만들고, 
방 조회 API에 추가했습니다.
DTO와 Util 위치는 충돌을 최대한 피하기 위해서 MemberStat 도메인에서 제작했습니다.
```java
// 
public class MemberStatDifferenceResponseDTO {
private List<String> blue;
private List<String> red;
private List<String> white;
}
```
```java
public static MemberStatDifferenceResponseDTO toMemberStatDifferenceResponseDTO(List<MemberStat> memberStatList) {
List<String> blue = new ArrayList<>();
List<String> red = new ArrayList<>();
List<String> white = new ArrayList<>();
Map<String, Function<MemberStat, Object>> fieldGetters = createFieldGetters();
for (String fieldName : fieldGetters.keySet()) {
DifferenceStatus status = compareField(memberStatList, fieldGetters.get(fieldName));
switch (status) {
case BLUE:
blue.add(fieldName);
break;
case RED:
red.add(fieldName); …
```
> [COZY-311] feat: 방 라이프스타일 일치 칩 조회하는 기능 추가(Room 조회 API에 통합)

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
MemberStat에 확인하지 못한 부분이 있어 수정했습니다.
빌드에 영향이 가 바로 머지하겠습니다.
죄송합니다.
> [COZY-318] fix: MemberStat 버그 수정

- src/main/java/com/cozymate/cozymate_server/domain/rule/dto/RuleRequestDto.java
단순 에러 해결입니다. 바로 머지하겠습ㄴ디ㅏ.
```java
```
>
> [COZY-304] fix: memo가 null이기에 발생하는 문제 해결

- src/main/java/com/cozymate/cozymate_server/domain/role/Role.java
- src/main/java/com/cozymate/cozymate_server/domain/role/controller/RoleController.java
- src/main/java/com/cozymate/cozymate_server/domain/role/converter/RoleConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/RoleRequestDto.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/RoleResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/Todo.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/converter/TodoTypeConverter.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- src/main/java/com/cozymate/cozymate_server/global/scheduler/NotificationScheduler.java
- Role에서 Assignee List로 관리하는걸로 수정했습니다.
- Role 조회 시 Role 기반으로 반환하는걸로 변경했습니다.
- Todo에 스케줄러로 추가하는 기능을 변경했습니다.
특이사항 이상 무.
매일하는 롤 추가
일정없는 롤 추가
바니한테 월요일마다 시킴
>
> [COZY-317] feat: ROLE 부분 기획 변경에 따른 기능수정

- src/main/java/com/cozymate/cozymate_server/domain/mate/converter/MateConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/enums/EntryStatus.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
1. 방장의 룸메이트 강제 퇴장 기능
2. 참여요청 기능
- 사용자: 참여 요청/취소
- 방장: 요청 수락/거절
3. 내방으로 초대 기능
- 방장: 내방으로 초대/취소
- 사용자: 초대 수락/거절
entryStatus에 INVITED 상태를 추가했습니다
방으로 초대하면 INVITED 상태가 되고,
사용자가 초대를 요청하면 PENDING 상태가 됩니다
```java
```
방장이 아닌데 퇴장시키려 할 때
해당 방의 룸메이트가 아닌 경우 / 이미 퇴장시켰거나 룸메이트가 아닌 사용자를 퇴장시키려 할 떄
자기 자신을 퇴장시키려 할 때
강제 퇴장 성공
성공
인원이 꽉찬 방에 요청할 때
이미 참여요청 했을 때
방장에 의해 이미 초대된 경우
참여 요청이 존재하지 않을 때
요청 취소 성공 => 거절시 DB에서 삭제
요청이 존재하지 않을 때
사용자가 방장이 아닐 때
사용자가 다른 방에 들어가있을 때
요청 수락 또는 거절 성공 => 거절시 DB에서 삭제
초대한 사용자가 속한 다른 방이 있을 때
초대 성공했을 때 => 초대받은 사용자가 수락할 때까지 INVITED 상태로 대기
방장이 아닌 사용자가 초대하려고 할 때
초대 요청이 존재하지 않을 때
방장이 아닐 때
초대 취소 성공 -> DB에서 삭제
초대요청이 존재하지 않을 때
방 정원이 꽉 찼을 때
다른 방에 이미 들어간 경우
초대요청 수락/거절 성공 => 거절시 DB에서 삭제
>
> [COZY-321] 강제퇴장 및 방 초대/참여 요청 기능 구현

- src/main/java/com/cozymate/cozymate_server/domain/member/repository/MemberRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
사용자 검색 기능 구현 완료했습니다.
..
본인 제외했습니다.
델로 쌍둥이 델로롱도 같이 검색이 잘 됩니다
끝 문자열도 검색 잘 됩니다
없습니다
> [COZY-326] feat: 사용자 검색 기능 구현 완료

- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
다른 사용자가 속한 방이 있는지 조회하는 기능입니다
기존에 있던 api를 이용해서 크게 다르지 않습니다
```java
```
속한방이 있으면 해당 방의 ID 리턴
없으면 0 리턴
>
> [COZY-327] feat: 다른 사용자가 속한 방 있는지 조회

- src/main/java/com/cozymate/cozymate_server/domain/member/converter/MemberConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/MemberRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/enums/Gender.java
- src/main/java/com/cozymate/cozymate_server/domain/member/enums/SocialType.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
기획 수정 되면서 회원 가입 로직이 날라갔었네여.. 수정했습니다!
요청이구요 
응답입입니다.
>
> [COZY-331] fix : 회원가입 오류 수정

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/MemberStatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/Room.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomRecommendController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomRecommendConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomRecommendResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/RoomResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/room/repository/RoomRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomRecommendService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomhashtag/RoomHashtag.java
- 방 추천 기능을 구현했습니다.
- 말 그대로 기능만 구현했고, 추가적인 작업이 추후 필요하긴 합니다.
- 일단 Room의 엔티티를 추가해서 필터링 작업도 진행해야하고... 예외처리와 Tuple 데이터 처리 등...
- 프론트에 배포할 수 있을 수준으로만 구현하였고, 추후 추가작업 진행하겠습니다.
```java
```
>
> [COZY-310] feat: 방 추천 기능 구현

- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteQueryService.java
- develop에서 에러가 발생해서 임시조치했습니다.
- @veronees 이후에 수정해주세요
```java
```
>
> [FIX-333] fix: 분기 이후로 수정된 클래스를 가져다 쓰다가 발생한 에러 해결

- src/main/java/com/cozymate/cozymate_server/domain/favorite/converter/FavoriteConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/favorite/dto/FavoriteResponseDto.java
- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteQueryService.java
1. 응답 dto 변환 과정에서 인자 하나 빼먹은 거 수정했습니다.
바로 머지할게요
```java
```
>
> [COZY-322] fix: 오류 수정

- src/main/java/com/cozymate/cozymate_server/global/logging/AopLogger.java
- src/main/java/com/cozymate/cozymate_server/global/logging/MdcLoggingInterceptor.java
로그 파일로 분석 구성해두려고합니다
> 고민사항도 적어주세요.
> [COZY-334] refac: 로그 형식 수정

- src/main/java/com/cozymate/cozymate_server/domain/member/converter/MemberConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/response/MemberDetailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/room/converter/RoomConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/room/dto/response/RoomDetailResponseDTO.java
넹
Room과 Member를 일단 우선적으로 Record로 변경하고, ResponseDTO와 관련 Conveter를 구성했습니다.
기본적으로 해당 엔티티가 가진 데이터만 반환하는것을 우선했습니다.
해당 DTO는 공통 응답이니, member에 대한 정보를 반환한다거나, Room에 대한 정보를 반환하려고 할 때 해당 DTO를 생성해서 넣어주면 되고 이외의 정보는 따로 넣어서 반환해주시면 되겠습니다.
해당 DTO 들 보고 많이 사용되는 데이터 여부에 따라서 해당 공통응답 DTO에 추가할지 뺄지 결정하겠습니다.
혹시나 이거 자주 사용되는 데이터다 싶은데, 없으면 알려주세요. 체크하고 반영할지 결정하겠습니당
> 고민사항도 적어주세요.
> [COZY-338] refac: Room, Member 공통 응답 DetailResponseDTO 구성 및 Converter 생성

- src/main/java/com/cozymate/cozymate_server/domain/auth/utils/JwtFilter.java
- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/university/controller/UniversityController.java
네
회원가입과정에서 임시토큰으로 접근 대학교 목록 조회 안되는 오류 수정
임시토큰 발급을 받아서
확인이 됩니다.
> 고민사항도 적어주세요.
> [COZY-337] fix : 임시토큰 허용 url에 대학교 목록 조회 추가

- src/main/java/com/cozymate/cozymate_server/domain/room/Room.java
- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
비공개방을 공개방으로 전환하는 기능입니다
```java
```
이미 공개방일 때
성공
방장이 아닐 때
룸메이트가 아닐 때

>
> [COZY-332] feat: 공개방 전환

- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
> [COZY-332] fix: 오류 수정

- src/main/java/com/cozymate/cozymate_server/domain/role/Role.java
- src/main/java/com/cozymate/cozymate_server/domain/role/controller/RoleController.java
- src/main/java/com/cozymate/cozymate_server/domain/role/converter/RoleConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/request/CreateRoleRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/response/RoleIdResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/Rule.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/controller/RuleController.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/converter/RuleConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/dto/response/RuleIdResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/service/RuleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/Todo.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/controller/TodoController.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/converter/TodoConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/dto/response/TodoIdResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
넹
- 현재 Todo Role Rule 부분의 String 길이가 제한이 없어서 default인 255로 되어있습니다
- Cozymate 기획상 기준으로 해당 제한을 추가했습니다. 추후 DB를 새로 구성할 때 적용될 예정이므로, 일단 지금은 DataGrip을 통해 속성 업데이트를 해두겠습니다.
> 고민사항도 적어주세요.
> [COZY-324] refac: Todo, Role Rule 엔티티 Varchar 사이즈 수정

- src/main/java/com/cozymate/cozymate_server/domain/role/converter/RoleConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/MateIdNameDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/response/RoleDetailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/converter/TodoConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/dto/response/TodoDetailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/dto/response/TodoMateListResponseDTO.java
> [COZY-354] refac: 반환값 수정

- .github/workflows/build_and_deploy.yml
- Dockerfile
네
로그 처리를 위해 도커 컴포즈를 구성했습니다.
> 고민사항도 적어주세요.
> [COZY-356] feat: docker-compose 구성

- src/main/java/com/cozymate/cozymate_server/domain/fcm/Fcm.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/controller/FcmController.java
1. fcm 토큰을 새로 받아도 등록되지 않은 토큰 에러가 계속 발생해서 포비가 알림 테스트에 사용하도록 임시 api하나 추가했습니다.
2. fcm 토큰 저장하는 로직에서 기존에 사용자가 갖고 있던 fcm토큰이 있으면 토큰 값만 업데이트했는데, isValid 필드도 true로 업데이트하도록 수정했습니다.
> 고민사항도 적어주세요.
> [COZY-362] test: 알림 보내는 테스트용 api 추가

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/util/MemberStatUtil.java
네
majorName이 없을 때, Collections.toMap이 null 값을 처리 못해서 해당 부분을 처리했습니다.
감사합니다
> [COZY-367] MemberStat getMemberStatFields NPE 해결

- build.gradle
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/Inquiry.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/controller/InquiryController.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/converter/InquiryConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/dto/request/CreateInquiryRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/dto/response/InquiryDetailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/enums/InquiryStatus.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/repository/InquiryRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/service/InquiryCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/service/InquiryQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- 매우 간단한 문의하기 API 구현했습니다.
가장 먼저 문의 내역 존재 여부 확인 시 - 문의 내역이 없기 때문에 false 반환
문의하기
이후 다시 문의 내역 존재 여부 확인 - true 반환
문의 내역 목록 조회
답변 대기 -> 답변 완료 (관리자용) - 이게 필요할까요
이후 문의 내역 목록 다시 조회
> 고민사항도 적어주세요.
> [COZY-371] feat : 문의하기 API

- build.gradle
넹
Sentry를 추가했습니다.
따로 구체적인 작업을 하지는 않았고, 단순 추적용으로만 추가해두었습니다.
에러 추적용으로만 생각했는데, 전반적인 로그 관리용이었네요 ㅇㅅㅇ
지금까지 쉘로 관리하던것보다 편의성이 월등하게 좋은거같아서, 장단점이나 괜찮은지 레퍼 좀 더 찾아보고 제가 좀 더 만질게용
> 고민사항도 적어주세요.
> [COZY-374] feat: Sentry 적용

- src/main/java/com/cozymate/cozymate_server/domain/role/controller/RoleController.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/MateIdNameDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/role/dto/request/CreateRoleRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
네
IOS에서 수정해달라고 요청한 부분입니다.
> 고민사항도 적어주세요.
> [COZY-377] refac: Role 생성, 수정 DTO 변경

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/querydsl/MemberStatQueryRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/querydsl/MemberStatQueryRepositoryImpl.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryService.java
네
pagable IsNext 에러 해결, 필터링 시 발생한 서버 오류 해결
hasNext가 진실을 고하고 있습니다.
일치율 2프로..도 존재하네요
눈꽃이랑 같은 오류 발생해 긴급 수정했습니다
감사합니다
> [COZY-375] feat: pagable IsNext 에러 해결, 필터링 시 발생한 서버 오류 해결

- src/main/java/com/cozymate/cozymate_server/domain/todo/controller/TodoController.java
- src/main/java/com/cozymate/cozymate_server/global/response/exception/ExceptionAdvice.java
- src/main/java/com/cozymate/cozymate_server/global/response/exception/GeneralException.java
넵
센트리 로깅 세팅하면서 에러 좀 정리했습니당
- printStackTrace 하던걸 그냥 가장 가까운 클래스만 가리키도록 수정
- 또 그냥 출력하던걸 log로 변경해서 [ERROR] 감싸서 출력하도록 수정
- 400번 에러는 INFO로 Sentry에 보내고, 500번 에러는 FATAL로 Sentry에 보냄
- 500번 에러는 보낼 때 message, location 값을 Additional로 추가해서 전송
- 400번 에러는 에러 메시지만 message로 Additional 추가해서 전송
깔꼼해졌죠?
> 고민사항도 적어주세요.
> [COZY-379] feat: Sentry 로깅 세팅

- src/main/java/com/cozymate/cozymate_server/domain/room/controller/RoomController.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
네
방장이 사용자한테 방 참여 요청을 보냈는지 여부 조회 API 입니다
방 참여 보냈을 때
안보냈을 때
방장이 아닐 때
> 고민사항도 적어주세요.
> [COZY-388] feat: 방장이 사용자한테 방 참여 요청을 보냈는지 여부 조회

- src/main/java/com/cozymate/cozymate_server/domain/member/Member.java
- src/main/java/com/cozymate/cozymate_server/domain/member/controller/MemberController.java
- src/main/java/com/cozymate/cozymate_server/domain/member/converter/MemberConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/request/SignInRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/request/SignUpRequestDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/response/MemberDetailResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/dto/response/SignInResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberQueryService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
네에
- 사용자 기본정보 수정 : persona, nickname, majorname, birthday
- 사용자 정보 조회 시 대학교 id 추가
베로로 바꿔 볼게여
:(
말랑카우로 바꿔볼게여
:)
말랑카우로 바뀐걸 볼 수 있습니다.
정보 조회시 대학교 id 도 반환합니다.
> 고민사항도 적어주세요.
> [COZY-385] feat : 사용자 기본 정보 수정 api 구현 및 기본 정보 조회시 대학교 Id 추가

- src/main/java/com/cozymate/cozymate_server/domain/mail/controller/MailController.java
- src/main/java/com/cozymate/cozymate_server/domain/mail/service/MailService.java
네
대충 메일을 인증했다라는 사실을 반환해주는 API입니다. 별거업성요
> 고민사항도 적어주세요.
> [COZY-397] feat: 메일 인증 여부 반환하는 API 구현

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/querydsl/MemberStatQueryRepositoryImpl.java
네
검색 결과가 중복으로 나오는 버그를 수정했습니다.
저도 겹치는게 있어서 확인해봤는데 이제 수정되었습니다.
감사합니다. 다음부터는 같은 경우의 수가 일어날 걸 고려해 여러 정렬 기준을 두는게 좋을 거 같네여
> [COZY-401] fix: Pagination 중복 해결한 코드 수정

- src/main/java/com/cozymate/cozymate_server/domain/chat/repository/ChatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/ChatRoom.java
- src/main/java/com/cozymate/cozymate_server/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/repository/FcmRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberWithdrawService.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstat/repository/MemberStatRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatequality/repository/MemberStatEqualityRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/memberstatpreference/repository/MemberStatPreferenceRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/repository/NotificationLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/post/repository/PostRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/postcomment/PostCommentRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/postimage/PostImageRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/report/repository/ReportRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/role/Role.java
- src/main/java/com/cozymate/cozymate_server/domain/role/repository/RoleRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/repository/RoomLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/Todo.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/repository/TodoRepository.java
회원 탈퇴 기능 구현 완료
```
2024-11-26 05:16:45,876 [http-nio-8080-exec-2] INFO  MemberWithdrawService          - 시작
2024-11-26 05:16:45,879 [http-nio-8080-exec-2] INFO  AopLogger                      - [FUNCTION] rid 3b432dd1-0f27-4f70-8513-af94e3b56a63 | func deleteById | time 15ms
2024-11-26 05:16:45,887 [http-nio-8080-exec-2] DEBUG SqlStatementLogger             - select t1_0.user_name,t1_0.created_at,t1_0.refresh_token,t1_0.updated_at from token t1_0 where t1_0.user_name=?
2024-11-26 05:16:45,903 [http-nio-8080-exec-2] INFO  AopLogger                      - [FUNCTION] rid 3b432dd1-0f27-4f70-8513-af94e3b56a63 | func deleteById | time 39ms
2024-11-26 05:16:45,904 [http-nio-8080-exec-2] DEBUG SqlStatementLogger             - select ma1_0.member_id,ma1_0.code,ma1_0.created_at,ma1_0.is_verified,ma1 …
```
> [COZY-384] feat : 회원 탈퇴 기능 구현

- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/repository/NotificationLogRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/service/NotificationLogQueryService.java
네
COZY_HOME, COZY_ROLE 알림은 조회 대상에서 제외했습니다.
너무 간단해서 패스할게요
확인했어요~
> 고민사항도 적어주세요.
쟤네는 저장할 필요도 없을 것 같은데 어떻게 생각하시나요?
> [COZY-413] fix: COZY_HOME, COZY_ROLE 카테고리는 알림 내역 조회 대상에서 제외

- src/main/java/com/cozymate/cozymate_server/global/response/exception/ExceptionAdvice.java
넵
- 로그  메시지 출력중에 에러가 발생하는게 있어서 그 부분 고치면서 Bean Validation 관련 에러 출력 형식도 좀 변경했습니다.
이런식으로 출력되는 로그가 있었는데
이렇게 바꼈습니당
또
이렇게 출력과정에서 문제가 발생하는게 있었는데
이렇게 변경되면서 좀 더 Validation 에러 형식을 명확하게 보여줍니다
> 고민사항도 적어주세요.
로그 출력중에 구조화되지 않은 부분이 발생하거나, 로그 부분에서 에러가 발생하면 바로 말해주세요
> [COZY-418] feat: 로그 반환 메시지 수정

- src/main/java/com/cozymate/cozymate_server/domain/mate/repository/MateRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/post/service/PostCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/postcomment/service/PostCommentCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/roomlog/service/RoomLogQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/service/RuleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/rule/service/RuleQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
넵
- 저의 멍청이슈로 인해서 발생한 에러를 해치웠습니다.
- EntryStatus에 대한 조건까지 사용해서 넣었습니다.
패스패스
> 고민사항도 적어주세요.
> [COZY-424] fix: findByRoomIdAndMateId 에러 해결

- src/main/java/com/cozymate/cozymate_server/domain/favorite/service/FavoriteQueryService.java
네
- 찜 사용자 조회 시 자신의 member stat이 조회되는 오류가 있었습니다
- 인자 순서 변경했어요
패스~
> 고민사항도 적어주세요.
> [COZY-423] fix: toMemberStatPreferenceDetailColorDTOList() 메서드 인자 순서 수정

- src/main/java/com/cozymate/cozymate_server/domain/favorite/repository/FavoriteRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/inquiry/repository/InquiryRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/member/Member.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/member/service/MemberWithdrawService.java
- memberStat과 Cascade 관계 지움
- Inquiry, Favorite 로직 추가
- 회원가입시 닉네임 검증 로직 추가
델로를 탈퇴 시켰습니다.
@veronees assign 받고 merge하겠습니다!
> [COZY-421] fix : 회원탈퇴 오류 수정

- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
방에서 나간 후 다시 방에 참여 요청하면 mate가 중복으로 생기는 문제를 고쳤습니다
나갔다가 재입장 요청했을때도 중복 메이트 안생기는 것 확인했습니다
> 고민사항도 적어주세요.
> [COZY-328] fix: 방 참여 요청시 EXITED 상태인 경우 재사용

- src/main/java/com/cozymate/cozymate_server/domain/fcm/controller/FcmController.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/FcmPushService.java
- src/main/java/com/cozymate/cozymate_server/domain/fcm/service/MessageUtil.java
- src/main/java/com/cozymate/cozymate_server/domain/notificationlog/enums/NotificationType.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/scheduler/NotificationScheduler.java
네
1. 자기한테 알림 오는거 토스트로 대체 (삭제 처리)
2. 코지메이트 투표 월말 알림 일단 x (주석 처리)
3. 초대 요청, 방 참여 요청 알림에 각각 방id, 멤버id 추가 전송
테스트 했습니다
> 고민사항도 적어주세요.
> [COZY-426] fix: 알림 수정 사항 반영

- src/main/java/com/cozymate/cozymate_server/domain/mail/service/MailService.java
> [COZY-448] fix : 애플 심사를 위한 테스트 메일 인증

- src/main/java/com/cozymate/cozymate_server/domain/auth/Token.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/repository/TokenRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/auth/service/AuthService.java
- src/main/java/com/cozymate/cozymate_server/domain/mail/service/MailService.java
- src/main/java/com/cozymate/cozymate_server/global/config/SshRedisConfig.java
리프레시 토큰 저장소를 rds 에서 redis로 변경했습니다.
제 리프레시 토큰은 레디스에 있습니다
> 고민사항도 적어주세요.
> [COZY-454]  feat : 토큰 위치 레디스로 수정

- .github/workflows/pr_review_reminder.yml
> [COZY-463] feat: 시간 수정 및 수동 실행방식 추가

- .github/workflows/pr_review_reminder.yml
> [COZY-463] feat: 깃허브 토큰 에러 수정

- .github/workflows/pr_review_reminder.yml
> [COZY-463] fix: json 파싱 에러 수정

- .github/CODEOWNERS
- .github/workflows/pr_review_reminder.yml
넵
Github Action을 생성했습니다.
앞으로 매일 정오에 해당 액션이 실행되고, PR마다 리뷰를 하지 않은 사람들에 대해서 멘션을 하게 됩니다.
매핑이 안되어있는 사람이 리뷰어로 등록되어있다면 해당 사람은 github 태그만 출력합니다.
정상 동작합니다~
> 고민사항도 적어주세요.
이러면 다들 잘 리뷰할 수 있겠죠?
> [COZY-463] feat: 매일 정오 PR 리뷰 리마인더 실행 액션 추가

- src/main/java/com/cozymate/cozymate_server/domain/mail/service/MailService.java
네
메일 인증에서 임시조치했습니다. 일단 진행할게요
> 고민사항도 적어주세요.
> [COZY-466] fix: 메일 인증 여부 반환에서 에러 임시조치

- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomQueryService.java
네
최신 develop에서 domitory 관련 에러가 발생해서, 서버가 실행되지 않는 모습을 발견했습니다.
수정해서 서버 동작까지 확인했습니다.
그리고 그런김에 data.sql에서 발생하는 에러도 안보이게 고쳤습니다.
> 고민사항도 적어주세요.
바로 머지할게용
> [COZY-503] fix: domitory 에러 해결

- src/test/java/com/cozymate/cozymate_server/domain/rule/service/RuleCommandServiceTest.java
- src/test/java/com/cozymate/cozymate_server/fixture/RoleFixture.java
- src/test/java/com/cozymate/cozymate_server/fixture/RoomLogFixture.java
- src/test/java/com/cozymate/cozymate_server/fixture/RuleFixture.java
- src/test/java/com/cozymate/cozymate_server/fixture/TodoFixture.java
넵
RuleCommandService 테스트 코드 작성
기존에 생성 관련 테스트가 있었고, 이번에 수정, 삭제 관련 테스트를 추가했습니다.
서비스단에서 코드가 단순하다보니 테스트할 거리가 많지 않았습니다.
> 고민사항도 적어주세요.
간단합니다... 테스트코드 작성을 좀 방치해뒀던거라... 앞으로 열심히 해볼게용
> [COZY-489] test: RuleCommandService 테스트 코드 작성

- src/test/java/com/cozymate/cozymate_server/fixture/TodoFixture.java
네
테스트코드가 실행이 안된다고 해서 수정했습니다.
일단 머지하고, 내일 픽스쳐 수정해서 다시 올리겠슴다
> 고민사항도 적어주세요.
> [COZY-515] test: 투두 픽스쳐 주석처리

- .github/CODEOWNERS
넵
깃헙 이름 바뀐사람 있어서 바꿧어요
> 고민사항도 적어주세요.
> [COZY-529] feat: CODEOWNER 수정

- src/test/java/com/cozymate/cozymate_server/fixture/RoomLogFixture.java
> [COZY-530] fix: RoomLog 엔티티에 todo -> todoId로 변경이 있음에 따라 발생한 테스트코드 에러 해결

- src/main/java/com/cozymate/cozymate_server/domain/role/Role.java
- src/main/java/com/cozymate/cozymate_server/domain/role/converter/RoleConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/role/repository/RoleRepository.java
- src/main/java/com/cozymate/cozymate_server/domain/role/repository/RoleRepositoryService.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandService.java
- src/main/java/com/cozymate/cozymate_server/domain/role/service/RoleQueryService.java
- src/main/java/com/cozymate/cozymate_server/domain/role/validator/RoleValidator.java
- src/main/java/com/cozymate/cozymate_server/domain/room/service/RoomCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
- src/test/java/com/cozymate/cozymate_server/domain/role/service/RoleCommandServiceTest.java
- src/test/java/com/cozymate/cozymate_server/domain/role/service/RoleQueryServiceTest.java
- src/test/java/com/cozymate/cozymate_server/domain/role/validator/RoleValidatorTest.java
넵
이전 PR과 동일합니다만, 무슨 오류인지는 모르겠는데, Squash로 햇는데 Commit Merge가 되어버려서 강머할게요...
진짜임...영상도 있음...
> 고민사항도 적어주세요.
> [COZY-536] refac: Role Validator 생성, Bitmask Converter 리팩토링 & RepositoryService 구성 (재 머지)

- src/main/java/com/cozymate/cozymate_server/domain/memberstat/memberstat/converter/MemberStatConverter.java
실수로 pr을 닫아서 다시 올립니다.
강머할게요..
> 고민사항도 적어주세요.
> [COZY-574] fix: 사용자 찜 목록 조회에서 MemberStat value를 String으로 변환하여 반환하도록 수정

- src/main/java/com/cozymate/cozymate_server/auth/controller/AdminAuthController.java
> [COZY-630] feat: redirect url 경로 수정

- src/main/java/com/cozymate/cozymate_server/domain/todo/service/TodoCommandService.java
- src/main/java/com/cozymate/cozymate_server/global/config/SecurityConfig.java
> [COZY-630] fix: CORS 수정 & Todo 알림 에러 수정

- src/main/java/com/cozymate/cozymate_server/domain/admin/report/converter/ReportAdminConverter.java
- src/main/java/com/cozymate/cozymate_server/domain/admin/report/dto/ReportAdminResponseDTO.java
- src/main/java/com/cozymate/cozymate_server/domain/admin/report/service/ReportAdminService.java
넵
- 프론트 요청에 따라 어드민 페이지에 isBanned 데이터를 추가했습니다.
> 고민사항도 적어주세요.
어드민이라서 그냥 머지할게용
> [COZY-653] feat: 어드민 신고 페이지 ban 여부 반환 추가
